### ISSUE TITLE
[Bug] with Taskbar Label

### ISSUE THREAD

**Issue by codezi** [ramensoftware/windhawk-mods#36] opened 2022-08-22 10:30 UTC
First of all, thank you very much for your awesome mod "Taskbar Label"
I installed this mod and it worked well.
But when we restart my PC, all apps pinned to the taskbar look like this:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/19167750/185900457-3ff24934-5536-427f-a675-7680b3b5601c.png">

<img width="281" alt="image" src="https://user-images.githubusercontent.com/19167750/185900019-f03a6162-6969-4263-be90-1c9ecdc55b9f.png">

**Comment by Tellinq** [comment] 2022-08-23 00:06
Also, when opening and closing pinned apps after a restart, the app boundry will slightly expand more than usual. I have to re-toggle the mod to fix this.
![image](https://user-images.githubusercontent.com/59412384/186040071-ea718dc8-ce66-4d09-85ce-e793684647cf.png)

While on the topic of taskbar label bugs: Notification icons don't seem to properly position. My guess is that Windows just made the icon based off the center and then move up to the right respectively. Unfortunately, Taskbar Label does not account for that.
![image](https://user-images.githubusercontent.com/59412384/186040598-b94834c0-bf90-494c-8763-35e15257ef98.png)

**Comment by thx1200** [comment] 2022-08-23 13:46
Same thing happening here to me.  Also when the taskbar is centered, the widget icon is not on the far left, but is instead in line with the rest of the icons.  I believe that is related to this issue.

![image](https://user-images.githubusercontent.com/5454591/186174539-0e9c9b73-f5cb-4b90-a8a4-5b8f2360a13b.png)

**Comment by Tellinq** [comment] 2022-08-24 03:27
Also, I did notice that when I have the mod enabled, Windows takes significantly longer to show the Lock Screen when turning on your PC. The same thing happens when loading explorer. Disabling the mod makes loading these two nearly instant for my system. For the record my OS drive has a WD Blue SN570 SSD. I highly doubt it's the SSD especially since toggling the mod on and off consistently gives me these results.

If I need to upload a recording, I will gladly do so, although to be fair it will have to be via phone since I don't have a capture card (at least for showing my system POSTing and going to the Lock Screen - I'll screen record for Explorer).

**Comment by m417z** [comment] 2022-08-25 06:52
I believe that the issue is fixed in version 1.0.1. Please try it.

> Notification icons don't seem to properly position. My guess is that Windows just made the icon based off the center and then move up to the right respectively.

I'll take a look.

> Also, I did notice that when I have the mod enabled, Windows takes significantly longer to show the Lock Screen when turning on my PC.

I believe that it's because of the symbol loading, which can be done only once and then cached. I'll look into implementing that.

**Comment by Tellinq** [comment] 2022-08-25 10:54
I was able to try it out on my laptop (22621.382) and pinned items keep their original width both when never opened and open -> closed. Looks like your fix for that worked!

Unfortunately I can't test on my main system yet due to Issue #40 but once that gets addressed I expect the fix to also apply to that.

**Comment by codezi** [comment] 2022-08-27 03:13
It seems not to work with the newest dev build when restarted.
Edition	Windows 11 Pro Insider Preview
Version	22H2
Installed on	‎27/‎08/‎2022
OS build	25188.1000
Experience	Windows Feature Experience Pack 1000.25188.1000.0

**Comment by Tellinq** [comment] 2022-09-02 21:39
I actually had a similar situation with 22622.590, which no matter how many times I restarted. The moment I went into one of the editors for a forked mod, everything started to work again. Pretty sure it's still related to #40.

As of right now all mods that worked previously still work for me.
![image](https://user-images.githubusercontent.com/59412384/188238836-834e73b7-aca6-4705-bac8-de6689002f80.png)

**Comment by codezi** [comment] 2022-09-21 17:27
It does not work with 
Edition	Windows 11 Pro Insider Preview
Version	22H2
Installed on	‎21/‎09/‎2022
OS build	25201.1000
Experience	Windows Feature Experience Pack 1000.25201.1000.0

**Comment by IlanZ93** [comment] 2023-01-09 09:56
Hello, i noticed when the taskbar is full and Taskbar Labels enabled, i dont have the "see more" dots. 

With mod enable :
![image](https://user-images.githubusercontent.com/23208231/211281750-b0530a6a-e70a-41e0-bdf5-6aed5cd3d9f9.png)

Without mod enable : 
![image](https://user-images.githubusercontent.com/23208231/211281832-ec979726-65f3-4079-8162-60df14e8f0cd.png)


Maybe in "Disable grouping on the taskbar" mod, you can add an option to group if taskbar is full.

Or just fix this issue 

Thank you !

**Comment by psorincatalin** [comment] 2023-02-28 11:23
> 

It's not just you, I have the exact same issue as of 28 Feb 2023.

**Comment by m417z** [comment] 2023-03-11 18:34
All the issues mentioned here were fixed in version 1.1 of the Taskbar Labels for Windows 11 mod. More details about the new version:
https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11

**Closed by m417z** 2023-03-11 18:34 UTC
Labels: mod-bug
