### ISSUE TITLE
[Windows 11 Start Menu Styler] no answer when press the letter

### ISSUE THREAD

**Issue by HMwancheng** [ramensoftware/windhawk-mods#715] opened 2024-06-01 14:06 UTC
https://github.com/ramensoftware/windhawk-mods/assets/91036325/bd17b892-6e14-45ed-8482-1e52965a8901

**Comment by HMwancheng** [comment] 2024-06-01 14:07
![image](https://github.com/ramensoftware/windhawk-mods/assets/91036325/02495890-e3a6-4e53-8af6-62ca7c6c7065)

**Comment by m417z** [comment] 2024-06-03 22:18
Thanks for the report. It's not a bug of the mod, it's a limitation of the [SideBySide2](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/SideBySide2/README.md) theme by @dreamsynth. I know that the author is working on a solution.

Since it's not a mod bug, I'm closing the issue.

**Closed by m417z** 2024-06-03 22:18 UTC
Labels: mod-bug
