### ISSUE TITLE
Taskbar height and icon size @m417z does not load after KB5040527 windows update

### ISSUE THREAD

**Issue by PeterTriac** [ramensoftware/windhawk-mods#807] opened 2024-07-26 11:21 UTC
Taskbar height and icon size @m417z does not load after KB5040527 windows update .
I uninstalled the update and everything worked as before. 
Windows 11 Pro 23H2
Thanks for reading !
---
I found this info (but not important :-) 

https://support.microsoft.com/en-us/topic/july-25-2024-kb5040527-os-builds-22621-3958-and-22631-3958-preview-de3e1e24-0c07-4210-9777-8e03a1446bae

When the taskbar has keyboard focus (WIN + T), you can press a letter, and you will go to the app whose name starts with that letter. When you press a letter more than once, you will go to the next app whose name starts with that letter. Pressing a letter more than once only works if there are multiple pinned or open apps whose name starts with that letter. If you are using an uncombined taskbar, when you press a letter, you go to the window whose name starts with that letter. Also, when you press Home and End, the keyboard focus changes to the first and last items in the taskbar.

**Comment by Farrukhw** [comment] 2024-07-26 12:56
Thanks. I'm facing the same. going to uninstall this windows update.

**Comment by PeterTriac** [comment] 2024-07-26 23:15
After uninstalling the Windows update...:
Shutting down the PC......:
"Critical error".
"Your Start menu is not working".
"An attempt will be made to fix this the next time you log on".
(not)

**Comment by m417z** [comment] 2024-07-27 12:11
Update KB5040527, which was released two days ago, introduced a change that made it incompatible with the mod. Should be fixed now in version 1.2.9.

Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/809.

**Closed by m417z** 2024-07-27 12:11 UTC
Labels: mod-bug

**Comment by PeterTriac** [comment] 2024-07-27 19:33
Everything works fine again !
