### ISSUE TITLE
Drag & Drop with mods 'Taskbar height and icon size' & 'Multirow taskbar for Windows 11' Only works on the SAME line

### ISSUE THREAD

**Issue by dbareis** [ramensoftware/windhawk-mods#1391] opened 2024-12-30 05:34 UTC
If I drag a program on line 1, I can drop it in whatever position I want on line 1 but can't drag it to line 2.

**Comment by m417z** [comment] 2024-12-30 06:13
That's a known limitation, closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/1350.

**Closed by m417z** 2024-12-30 06:13 UTC
Labels: mod-enhancement
