### ISSUE TITLE
[Taskbar Labels for Windows 11] add group feature for Newer Windows 11 versions

### ISSUE THREAD

**Issue by JTFA** [ramensoftware/windhawk-mods#662] opened 2024-05-05 06:40 UTC
![图片](https://github.com/ramensoftware/windhawk-mods/assets/57850248/6792a5d4-ee0b-4647-a37e-4119b8997fb1)
It seems that the new version of Win11 can't realize the effect of showing the name of the apps and merging the same apps into one button at the same time as shown in the picture, I hope this feature can be added.

**Comment by m417z** [comment] 2024-06-03 22:13
Thanks for the feedback. Closing as a duplicate of #425.

**Closed by m417z** 2024-06-03 22:13 UTC
Labels: mod-enhancement
