### ISSUE TITLE
Slick Window Arrangement: Windows freeze when trying to snap, occasional crashes

### ISSUE THREAD

**Issue by TheChilliPL** [ramensoftware/windhawk-mods#56] opened 2022-11-03 15:22 UTC
When the Slick Window Arrangement mod is on (with the default settings), I experience occasional freezes: when trying to snap a window to the edge of the screen, the window sometimes stays in place, with the semi-transparent target overlay still visible.

Snapping with Win+arrows still works.
Occasionally, it may crash some system process. I'd guess it crashes explorer.exe if not for the fact that when it happens, the whole screen goes black for several seconds, and after the image is back, the snapped window starts making the cursor invisible when it's hovered.
To fix the cursor invisibility issue, I have to restart the program so that a new window is opened.
It seems to happen more often with some specific programs—it happens almost constantly with the Vivaldi browser—although occasionally may happen with any.

It happens on two machines, a PC and a laptop, both running Windows 11 dev insider on different versions, and the issue has been going on for a while, with various OS builds. Windhawk got installed on the laptop around 2 weeks ago, although on PC the issue was already there at that moment.

**Comment by m417z** [comment] 2022-11-04 16:05
I'm using the latest non-insider Windows 11 version (22H2) with the Slick Window Arrangement mod, and I haven't experienced these kinds of issues. If you have a way to reproduce the problem, please let me know and I'll try to see what's going on.

Also, creating a dump of the crashing explorer.exe process might help shed some light. Can you please create a crash dump and send it to me (you can find my email [here](https://ramensoftware.com/contact))? You can use ProcDump. Run `procdump64.exe -mp -e explorer.exe` and trigger the crash. The dump will be written to a file, the details will be printed in the ProcDump console window.

**Comment by drygoatair** [comment] 2023-10-01 07:45
> When the Slick Window Arrangement mod is on (with the default settings), I experience occasional freezes: when trying to snap a window to the edge of the screen, the window sometimes stays in place, with the semi-transparent target overlay still visible.
I occasionally experience this issue. Although, not the crashing part. It seems to mostly affect windows that are not native Windows windows. Down here is a screenshot of it happening with VSCodium:

![image](https://github.com/ramensoftware/windhawk-mods/assets/30617721/86dd563c-41da-497d-9a81-ad3d0a530198)

Using Win+arrow key fixes it temporarily though.

**Comment by m417z** [comment] 2023-10-01 07:50
I encountered this bug once or twice, but I didn't see it for a long time, probably not within the last year. If you find a way to reproduce it, let me know. I don't think the issue is directly caused by Slick Window Arrangement, but perhaps it makes it more likely to trigger as it causes more window movement events.

**Comment by liweichen6** [comment] 2024-09-12 19:40
Seems to be reproducible when the window size is the same as the target size (random thoughts: maybe this way, there's no resize needed, only snap).
I did that using Chrome/Windhawk/Discord, but it's easier to do so using the latter two, as their window sizes permanently change after minimize/recover.

https://github.com/user-attachments/assets/d767882f-3117-4497-ae9e-76c7365202eb

**Comment by JosueMeserom** [comment] 2024-09-29 17:22
> Seems to be reproducible when the window size is the same as the target size (random thoughts: maybe this way, there's no resize needed, only snap).
Yes, I have exactly the same problem, and the same way to reproduce it. It's annoying sometimes, because otherwise this is a fantastic module (and program).

**Comment by m417z** [comment] 2024-10-01 06:07
@liweichen6 thanks for coming up with reproduction steps after all these years! Fixed in Slick Window Arrangement v1.0.2. Regarding crashes, if it's still an issue please create a new issue with the relevant details.

**Closed by m417z** 2024-10-01 06:07 UTC
Labels: info-needed, mod-bug
