### ISSUE TITLE
[Mod Request] - Customize Taskbar Location

### ISSUE THREAD

**Issue by xntzmk** [ramensoftware/windhawk-mods#291] opened 2023-09-10 07:11 UTC
I would like to move the Windows 11 taskbar to another location, like the top 
(not using the old taskbar instead)

**Comment by m417z** [comment] 2024-06-25 03:49
Thanks for the suggestion. Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/166 and https://github.com/ramensoftware/windhawk-mods/issues/731.

**Closed by m417z** 2024-06-25 03:49 UTC
Labels: new-mod-idea
