### ISSUE TITLE
[taskbar-start-button-position] also left align the search and task view buttons

### ISSUE THREAD

**Issue by LEveLiQ** [ramensoftware/windhawk-mods#1277] opened 2024-11-25 04:11 UTC
@m417z the title is pretty much self explanatory, would be cool if I could also left align the search and task view buttons, similar to TaskbarX.

**Comment by m417z** [comment] 2024-11-29 02:02
Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/990.

**Closed by m417z** 2024-11-29 02:02 UTC
Labels: mod-enhancement
