### ISSUE TITLE
"Taskbar height and icon size" breaks the clock

### ISSUE THREAD

**Issue by vittbol** [ramensoftware/windhawk-mods#249] opened 2023-06-24 14:22 UTC
```
DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
11:21:17.725 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
11:21:17.725 8968 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.3.1
11:21:17.725 8968 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: taskbar-icon-size
11:21:17.725 8968 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.2
11:21:17.741 8968 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFE032A0000
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
11:21:17.742 8968 explorer.exe  [WH] [taskbar-icon-size] [807:Wh_ModInit]: >
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: IconSize
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: IconSize
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 25
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarHeight
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarHeight
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 35
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarButtonWidth
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarButtonWidth
11:21:17.742 8968 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 44
11:21:17.742 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-Taskbar.View.dll
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 1#1682034385#6828032#public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const #199568#public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)#1017552#public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)#1702796#private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)#2889948#__real@4048000000000000#5718640#public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const 
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDD9ED0B90
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A13F0
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDD9ED0B90: public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const 
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDD9F986D0
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A1770
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDD9F986D0: public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDDA03FB8C
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A17C0
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDDA03FB8C: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDDA1618DC
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A1840
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDDA1618DC: private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [496:operator()]: Found 00007FFDDA414270: __real@4048000000000000
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [496:operator()]: Found 00007FFDDA383A4C: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const 
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDDA158628
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A17E0
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDDA158628: private: double __cdecl winrt::SystemTray::implementation::SystemTrayController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDDA028C64
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A1910
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDDA028C64: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::Height(double)const 
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDD9FDFFF0
11:21:17.743 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A18A0
11:21:17.743 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.743 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDD9FDFFF0: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDD9FBE168
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A17A0
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDD9FBE168: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-Taskbar.dll
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 1#715376749#3575808#void __cdecl IconUtils::GetIconSize(bool,enum IconUtils::IconType,struct tagSIZE *)#1393024#public: virtual bool __cdecl IconContainer::IsStorageRecreationRequired(class CCoSimpleArray<unsigned int,4294967294,class CSimpleArrayStandardCompareHelper<unsigned int> > const &,enum IconContainerFlags)#1370240
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDDBAB4180
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A16F0
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDDBAB4180: void __cdecl IconUtils::GetIconSize(bool,enum IconUtils::IconType,struct tagSIZE *)
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFDDBAAE880
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A1750
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [taskbar-icon-size] [492:operator()]: Hooked 00007FFDDBAAE880: public: virtual bool __cdecl IconContainer::IsStorageRecreationRequired(class CCoSimpleArray<unsigned int,4294967294,class CSimpleArrayStandardCompareHelper<unsigned int> > const &,enum IconContainerFlags)
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFE0D24E4E0
11:21:17.744 8968 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFE032A1980
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
11:21:17.744 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
11:21:17.764 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::AfterInit
11:21:17.764 8968 explorer.exe  [WH] [taskbar-icon-size] [836:Wh_ModAfterInit]: >
11:21:17.766 8968 explorer.exe  [WH] [taskbar-icon-size] [252:TaskbarConfiguration_GetFrameSize_Hook]: >
11:21:17.766 8968 explorer.exe  [WH] [taskbar-icon-size] [274:TaskbarFrame_Height_double_Hook]: >
11:21:17.766 8968 explorer.exe  [WH] [taskbar-icon-size] [222:SystemTrayController_GetFrameSize_Hook]: >
11:21:17.932 8968 explorer.exe  [WH] [taskbar-icon-size] [252:TaskbarConfiguration_GetFrameSize_Hook]: >
11:21:17.932 8968 explorer.exe  [WH] [taskbar-icon-size] [274:TaskbarFrame_Height_double_Hook]: >
11:21:17.932 8968 explorer.exe  [WH] [taskbar-icon-size] [222:SystemTrayController_GetFrameSize_Hook]: >
11:21:18.197 8968 explorer.exe  [WH] [taskbar-icon-size] [252:TaskbarConfiguration_GetFrameSize_Hook]: >
11:21:18.197 8968 explorer.exe  [WH] [taskbar-icon-size] [274:TaskbarFrame_Height_double_Hook]: >
11:21:18.197 8968 explorer.exe  [WH] [taskbar-icon-size] [222:SystemTrayController_GetFrameSize_Hook]: >
11:21:18.197 8968 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::AfterInit
```

https://i.imgur.com/Ui8uaqQ.png

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/c46ac2f4-04b5-4866-bc71-f3e7af11c71e)

**Comment by vittbol** [comment] 2023-06-24 14:38
Also, my windows is windows 11 version 22H2 and have all the updates so far.

**Comment by m417z** [comment] 2023-06-28 11:50
Are you sure that you have all updates? Did you make any changes to the taskbar, for example with ViveTool or a third party tool?

Your notification area looks like an old version. For example, the `1` digit on your clock doesn't have the bottom underline. See:
https://www.reddit.com/r/Windows11/comments/zfkup4/did_they_change_the_font_for_the_taskbar_clock_in/

See also my comment here: https://github.com/ramensoftware/windhawk-mods/issues/149#issuecomment-1502927597

**Comment by squareloop1** [comment] 2023-09-29 05:08
Having the same issue on a multi monitor setup. Clock is nudged down on secondary monitors but fine on primary monitor. I am on the current Windows 11 Moment 4 Update.

**Comment by m417z** [comment] 2023-09-29 23:23
@squareloop1 while it looks similar, that's a different issue that requires a different fix. Please create a new issue for it.

**Comment by m417z** [comment] 2023-09-29 23:24
Regarding this issue, I'm closing it as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/149.

**Closed by m417z** 2023-09-29 23:24 UTC
Labels: mod-bug
