### ISSUE TITLE
Better file sizes in Explorer details

### ISSUE THREAD

**Issue by mirt81** [ramensoftware/windhawk-mods#1222] opened 2024-11-09 12:48 UTC
Copy Folders with Detailed Infos open show verry wrong Foldersize . . . 

Th@nks !

**Comment by m417z** [comment] 2024-11-09 12:50
Please post more details and a screenshot. What do you mean by "Copy Folders with Detailed Infos"? What do you mean by "verry wrong Foldersize"?

**Comment by mirt81** [comment] 2024-11-09 14:08
![Screenshot 2024-11-09 150415](https://github.com/user-attachments/assets/f28dd9bb-ab69-401d-9551-0afd86ae1d3d)

This is also when empty Recycle . . . sorry English not my main Speeching .

**Comment by mirt81** [comment] 2024-11-09 14:23
This is Only when Copy Folders single or muliple Files are Shown correct ! ?

**Comment by mirt81** [comment] 2024-11-09 14:33
[Log.txt](https://github.com/user-attachments/files/17687984/Log.txt)

**Comment by mirt81** [comment] 2024-11-09 15:01
If toggeling the "Use MB/GB for large files" turned on or of there is differnce for wrong shown Size . . . one shows much more size and other less much more wrong size.

Whish a good Time !

**Comment by m417z** [comment] 2024-11-09 15:27
Thanks, from my tests it's not related to "Use MB/GB for large files", only to "Show folder sizes". Fixed in version 1.5.2, please try it and confirm that the issue is fixed.

**Closed by m417z** 2024-11-09 15:27 UTC
Labels: mod-bug

**Comment by mirt81** [comment] 2024-11-09 16:12
IT´s fixed . . . really Speeedy with "Everything" now !
