### ISSUE TITLE
Taskbar on top for Windows 11: top-tray icons are bugged

### ISSUE THREAD

**Issue by Cubody** [ramensoftware/windhawk-mods#1084] opened 2024-10-15 07:00 UTC
When using Taskbar on top for Windows 11:
If you right-click on one of the tray icons in the group (sounds, wi-fi, battery), the window opens, but does not respond, you cannot select anything.

P. S. Is it possible to disable groupping for these three icons? I really dislike windows 11 sound panel and want to use another from windows store...

**Comment by m417z** [comment] 2024-10-15 08:27
> If you right-click on one of the tray icons in the group (sounds, wi-fi, battery), the window opens, but does not respond, you cannot select anything.

A duplicate of https://github.com/ramensoftware/windhawk-mods/issues/1055. Meanwhile, you can use the keyboard.

> P. S. Is it possible to disable groupping for these three icons? I really dislike windows 11 sound panel and want to use another from windows store...

Yes, you can use the [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler) mod, see:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide/blob/main/README.md#hide-the-volume-icon

**Closed by m417z** 2024-10-15 08:27 UTC
Labels: mod-bug
