### ISSUE TITLE
[Taskbar Labels for Windows 11] taskbar icon badges missaligned with custom icon padding

### ISSUE THREAD

**Issue by chrisf-pilot** [ramensoftware/windhawk-mods#610] opened 2024-04-22 03:59 UTC
@m417z 
![image](https://github.com/ramensoftware/windhawk-mods/assets/166574259/4d2baa7c-23ca-47c6-bfd0-d630eb728f0a)
My current settings are `{"taskbarItemWidth":0,"minimumTaskbarItemWidth":50,"maximumTaskbarItemWidth":176,"runningIndicatorStyle":"centerDynamic","progressIndicatorStyle":"sameAsRunningIndicatorStyle","fontSize":12,"leftAndRightPaddingSize":4,"spaceBetweenIconAndLabel":2,"labelForSingleItem":"%name%","labelForMultipleItems":"[%amount%] %name%"}`

I like shrinking the padding to fit more on my limited screenspace, but the badges aren't taking into account the new padding.

Also, how hard is it to alter the start button size as now the icon is smaller, it's button looks too big...?

**Comment by m417z** [comment] 2024-04-22 07:11
I'll look into adjusting the badge. Meanwhile, you might want to try looking into the [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler) mod, which can help adjust both the badge placement and the start button padding.

**Comment by Tiger-Heli** [comment] 2024-05-20 11:56
Just to help in the mean time ...
I ran into the same issue and solved it with Taskbar Styler. For me, the settings were:

Target:
Windows.UI.Xaml.Controls.Image#OverlayIcon
Style:
Margin=-16,0,0,0

You may need a different negative margin depending on what you set your icon sizes to.

**Comment by m417z** [comment] 2024-09-29 06:52
I believe it's fixed now in version 1.3.1 of the mod. Let me know if there are cases in which the issue isn't fixed.

**Closed by m417z** 2024-09-29 06:52 UTC
Labels: mod-bug

**Comment by Marshall-Brooks** [comment] 2024-09-30 11:29
Confirmed fixed with 1.3.1. I have two primary applications that use these - as above, I was fixing them with Taskbar Styler. I was able to turn that off and the overlays are still correctly positioned. Also, the overlays are still correctly positioned with the Taskbar Styler changes applied, so the two changes do not conflict with each other.
