### ISSUE TITLE
[Taskbar Labels for Windows 11] OnClick window dont show up

### ISSUE THREAD

**Issue by Madgique** [ramensoftware/windhawk-mods#1126] opened 2024-10-22 18:20 UTC
I don't know if this behavior is intended or not but when the Windows settings "Combine taskbar buttons"(sorry if it is not exactly this one mine is in French "Combiner les boutons de la barre des tâches et masquer les étiquettes") is on "Always", when I click on the uncombined windows it show preview instead of showing the window content but if this settings is on Never it works fine.

Intended : 

https://github.com/user-attachments/assets/c795b3a0-3f8d-4a6f-9c97-6ea1f9356035

https://github.com/user-attachments/assets/2d5890f7-762c-4bdd-9196-94f30d3c6cb3

**Comment by m417z** [comment] 2024-10-23 17:05
Thanks for the report. It's not the intended behavior. I'll look into fixing it in the next version.

**Comment by m417z** [comment] 2024-12-04 13:59
Fixed in version 1.3.3.

**Closed by m417z** 2024-12-04 13:59 UTC
Labels: mod-bug
