### ISSUE TITLE
[Windows 11 Start Menu Styler] Minor issues in Dev channel

### ISSUE THREAD

**Issue by yannouuuu** [ramensoftware/windhawk-mods#611] opened 2024-04-22 13:27 UTC
# Windows 11 Start Menu Styler

Hi @m417z, the mod is amazing but there are a few glitches:
- when you open a folder and close it, the started menu jumps around
- the write indicator in the search bar is incorrectly positioned

I hope this helps, and will be happy to answer any questions you may have.

### [[see recording below](https://github.com/ramensoftware/windhawk-mods/assets/76118368/f13e3ee9-f4f9-4c30-9493-093c83153df9)]
https://github.com/ramensoftware/windhawk-mods/assets/76118368/f13e3ee9-f4f9-4c30-9493-093c83153df9

**Comment by m417z** [comment] 2024-04-22 13:31
Hi, thanks for the feedback. I can't reproduce the problems on my computer. What's your Windows 11 version?
Also, the theme was created by Pyxisynth ([theme link](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/SideBySide2/README.md)). I'm not sure they have a GitHub account, but I'll let them know in Windhawk's Discord server.

**Comment by m417z** [comment] 2024-07-28 18:15
Many fixes were made in Windows 11 Start Menu Styler v1.1.5, at least some of the issues reported here as well, so I'm closing this issue. Generally, these are theme issues, not mod issues, so for other problems please create an issue here:
https://github.com/ramensoftware/windows-11-start-menu-styling-guide/issues

**Closed** 2024-07-28 18:15 UTC
Labels: mod-bug
