### ISSUE TITLE
[Taskbar notification icon spacing] change padding/margin between groups

### ISSUE THREAD

**Issue by ttodua** [ramensoftware/windhawk-mods#1011] opened 2024-09-29 12:04 UTC
@m417z 
this mod works for icons, but can you add an option to also change (reduce) the padding as you see in this scrsht:
![image](https://github.com/user-attachments/assets/d27a850c-5295-45b3-a3de-3bec097b6e5e)

see how much spacing (padding) has `ENG` aside

**Comment by m417z** [comment] 2024-09-29 13:49
Thanks for the feedback. Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/506.

**Closed by m417z** 2024-09-29 13:49 UTC
Labels: mod-enhancement
