### ISSUE TITLE
[Taskbar height and icon size] It doesn't work after Windows installed the latest update [KB5035942]

### ISSUE THREAD

**Issue by boyangma** [ramensoftware/windhawk-mods#579] opened 2024-03-27 03:24 UTC
Again and again, it does not work after Windows update.

**Comment by techswede** [comment] 2024-03-27 06:38
Same for me here. Win 11 Pro

**Comment by jibnew** [comment] 2024-03-27 07:42
Confirmed, same here

**Comment by groovyclam** [comment] 2024-03-27 18:44
Same here - and also the "Taskbar Clock Customisation" mod is failing 

Win 11 Home

**Comment by vinhpham4895** [comment] 2024-03-28 04:27
Confirmed, most taskbar mods no longer work

**Comment by clover-yan** [comment] 2024-03-28 07:10
@m417z Yes, `KB5035942`, which is being pushed onto stable channel, broke Windhawk mods.

I use Taskbar Clock and Taskbar Label mods, they're broken as well. In the 'Loaded Mods' window, I can see them marked as 'unloaded'. 

By the way, no matter why, this update also brought my Copilot on the taskbar away.

I've rolled back the update, and I can access the mods and Copilot now.

**Comment by m417z** [comment] 2024-03-28 07:41
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by groovyclam** [comment] 2024-03-28 10:26
It's fixed on my Win 11 Home. I don't understand why this worked but I downloaded 1.4.1 install. Did a reinstall ( not deinstalling first ). At fist nothing appeared fixed.
I rebooted a couple of times. No joy. I exited the autoloaded startup Windhawk in my tasktray of the running 1.4.1 and then clicked on the new Windhawk icon the reinstall had made on my desktop.
A small window opened near my taskbar clock saying something like "reloading symbols" for the two mods I used. And then it started working. My two mods (Taskbar Icon Size) and (Taskbar Clock Customisation) did the changes they were set to do. 
It survives a reboot.

**Comment by m417z** [comment] 2024-03-28 21:52
I assume that, as it happened with some previous updates, it took some time for Microsoft to publish debug symbols which are required for some of the mods to work. From the [Troubleshooting](https://github.com/ramensoftware/windhawk/wiki/Troubleshooting) page:

> Sometimes, it takes some time (usually no more than a day or two) for symbols to become available after an update is published. For some Windows builds, Microsoft doesn't publish debug symbols at all (rare, but happened in the past).

Since it's reported to be working in the last comment, I'm closing this issue. If disabling and re-enabling the mods, or exiting and restarting Windhawk doesn't work for you, please leave a comment along with the debug logs.

**Closed by m417z** 2024-03-28 21:52 UTC
Labels: mod-bug
