### ISSUE TITLE
[Windows 11 Taskbar Styler] Doesn't work properly on 2 monitors.

### ISSUE THREAD

**Issue by kaer1a** [ramensoftware/windhawk-mods#1124] opened 2024-10-22 17:20 UTC
uh pretty much the title.
i have a theme (attached) and it breaks whenever i connect my other monitor.
![image](https://github.com/user-attachments/assets/af360b17-fad1-4e80-a4d2-8f96a2e10c40)

it also loses the 'acrylic' blur and i have to reapply the theme/mod everytime i disconnect my other monitor

**Comment by m417z** [comment] 2024-10-22 17:24
A duplicate of https://github.com/ramensoftware/windhawk-mods/issues/742.

**Closed by m417z** 2024-10-22 17:24 UTC
Labels: mod-bug
