### ISSUE TITLE
Windows 11 Taskbar Styler

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#798] opened 2024-07-20 22:36 UTC
The Windows 11 Taskbar Styler mod has theme bugs since the latest update for me.

transcluscenttaskbar:
![image](https://github.com/user-attachments/assets/fc945f0b-15e6-48ef-9916-43d198139aa8)
squircle:
![image](https://github.com/user-attachments/assets/f6a886f4-b26c-485d-8d54-24990c172c3c)
rosepine:
![image](https://github.com/user-attachments/assets/85f0f463-4eb5-4286-94dd-d2b32e5ab7f3)
@m417z

**Comment by m417z** [comment] 2024-07-20 22:39
Please see the discussion here:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/46

The themes were updated. You can revert to the old themes manually for now.

The change in TranslucentTaskbar was intended. What is the issue with the other themes?

**Comment by gilnett** [comment] 2024-07-20 22:52
For Rose Spine, I just thought it wasn't normal to be without the Start button. For Squircle, I don't have any circles anymore. And for TranslucentTaskbar, it's my fault; the battery saver was enabled.

**Comment by m417z** [comment] 2024-07-20 23:17
All these seem like deliberate changes to the themes by their authors. You can find the author of each theme here by clicking on the theme:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide?tab=readme-ov-file#themes

Since it's not about the core mod functionality, I'm closing this issue. You can join the discussion in the link I mentioned above, and we can perhaps come up with a better version for the themes.

**Closed by m417z** 2024-07-20 23:17 UTC
Labels: mod-bug
