### ISSUE TITLE
[Disable grouping on the taskbar] Applications keep reappearing at the end of the taskbar

### ISSUE THREAD

**Issue by Aleksanderis** [ramensoftware/windhawk-mods#461] opened 2024-01-03 20:09 UTC
@m417z

**Description**
Pinned applications reappear at the end of the taskbar after PC was locked and then unlocked if multiple instances of the same application were opened.
Initially I was thinking it was same issue as #423, but after the fix I'm still able to reproduce it. I tried different "Pinned items mode" options, also tried to restart explorer.exe, Windhawk, etc - and was still able to reproduce the issue.

**Technical information**
* Multi-monitor setup
* Windows 11 with latest updates
* Windhawk mods installed: "Disable grouping on the taskbar" (version 1.3.1), "Middle click to close on the taskbar", "Open pinned items with double click"

**Reproduction steps**

* Open a pinned application (i.e. Windows Explorer)
* Open a second instance of it
* Lock PC (Win + L)
* Application instances are on same monitor (primary)
* (Not sure if it's important, but I also wait until monitors go to sleep which might alter how Windows treats primary/secondary monitors)

**Result**

Application icon has a little bounce and moved to the end of the taskbar. Originally pinned item is gone.
This is how it works under normal conditions, everything is good:
![image](https://github.com/ramensoftware/windhawk-mods/assets/2393205/67c7e25f-6d41-4be8-9cd5-93ae107fac76)

Then I lock my PC, monitors go to sleep (it might be also important), and after I unlock PC I see this - all multi-windowed apps are moved to the end of the taskbar (ignore "Snipping Tool" at the end, it was opened later), so I need to rearrange everything manually every time:
![image](https://github.com/ramensoftware/windhawk-mods/assets/2393205/15db18ef-86f7-4bf3-8a3e-dbeb43b2d9c6)

Seems like it can be reproduced with all applications (including Windows Explorer) - all applications appearing at the end of the taskbar:
![image](https://github.com/ramensoftware/windhawk-mods/assets/2393205/cc0102b3-6f90-4fd8-b8f7-af17085a7e51)

**Expected**
* Application stays at the same position in the taskbar even if there are multiple instances opened.

**Comment by Aleksanderis** [comment] 2024-02-14 05:34
@m417z were you able to reproduce it? Or should I try giving more details?
Actually my described issue with duplicated is just part of the problem, later if such state preserved for a longer - even when apps are closed, they might be still left duplicated in the taskbar and only Explorer kill/restart helps resolve it.

**Comment by m417z** [comment] 2024-03-08 18:12
Sorry, I was busy with other things.

> - Open a pinned application (i.e. Windows Explorer)
> - Open a second instance of it
> - Lock PC (Win + L)
> - Application instances are on same monitor (primary)
> - (Not sure if it's important, but I also wait until monitors go to sleep which might alter how Windows treats primary/secondary monitors)

Here's my attempt at reproducing it. Did I miss something in one of the steps?
https://github.com/ramensoftware/windhawk-mods/assets/4129781/8f2f4ee9-b6c0-4e1b-8a30-34b51a9423ef

**Comment by m417z** [comment] 2024-06-01 10:48
I tried that, but without success. See the video recording below.
Any other ideas?

https://github.com/ramensoftware/windhawk-mods/assets/4129781/ca8d6247-cb34-4f0b-8ca5-04c3379b48f7

**Comment by m417z** [comment] 2024-06-01 12:36
I was able to reproduce the re-ordering with this option:
> When using multiple displays, show my taskbar apps on: Taskbar where window is open

I was also able to reproduce re-ordering without the mod. Without the mod, it seems that all pinned items go to the left, and all unpinned items go to the right.

With the mod, multiple instances, even if pinned, act as unpinned and go to the right. I think the root cause is similar to the one in this issue: https://github.com/ramensoftware/windhawk-mods/issues/690

I'll investigate more, and hopefully I'll find a solution to both issues.

**Comment by m417z** [comment] 2024-06-02 19:52
I spent some time trying to fix it, more time than I hoped.
Here's a version of the mod with the changes. Please install it and confirm that it fixes the issue. Also, let me know if you encounter any new issues.
https://github.com/m417z/my-windhawk-mods/blob/e16c05b77bd71bb8850e18b01f42305002c983db/mods/taskbar-grouping.wh.cpp

To install it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the content from the link above, click "Compile Mod", then "Exit Editing Mode".

**Comment by Aleksanderis** [comment] 2024-06-03 04:14
> I spent some time trying to fix it, more time than I hoped. Here's a version of the mod with the changes. Please install it and confirm that it fixes the issue. Also, let me know if you encounter any new issues. https://github.com/m417z/my-windhawk-mods/blob/e16c05b77bd71bb8850e18b01f42305002c983db/mods/taskbar-grouping.wh.cpp
> 
> To install it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the content from the link above, click "Compile Mod", then "Exit Editing Mode".

Nice work! I tried it and it looks really promising - I cannot reproduce the issue at least with my basic reproduction steps.
I will try it out and monitor it for a bit more extended period of time, then I will report here back.

**Comment by Aleksanderis** [comment] 2024-06-07 04:43
Running it for a few days and it looks really much more stable. Only once I noticed that pinned item got duplicated in the taskbar - one icon for an opened window + one icon as it would appear when application is not started. However after that it didn't recur for now. So even if it's some small bug - it's not as frustrating as the often icons reshuffling. :)

**Comment by m417z** [comment] 2024-06-08 08:28
Great, thanks for trying it. I released version 1.3.3. Regarding the bugs that you mentioned, bummer, I hoped that bugs such as duplicated pinned items are now fixed. If you find a way to reproduce it, please let me know.

**Closed by m417z** 2024-06-08 08:28 UTC
Labels: mod-bug
