### ISSUE TITLE
Taskbar notification icon spacing    downsize the input indicate

### ISSUE THREAD

**Issue by HMwancheng** [ramensoftware/windhawk-mods#623] opened 2024-04-26 13:19 UTC
Did can try to  downsize the input indicate?
TKS
It's will looks more beautiful !

![image](https://github.com/ramensoftware/windhawk-mods/assets/91036325/b78ca370-600f-4c72-9c2b-e810dfd0ebec)
![image](https://github.com/ramensoftware/windhawk-mods/assets/91036325/b565e41d-9b1f-43a7-9b44-bd53b84e06ab)
![image](https://github.com/ramensoftware/windhawk-mods/assets/91036325/250bcbf8-d570-4a88-84ad-e94eba66cc4e)

**Comment by m417z** [comment] 2024-04-26 17:12
Thanks for the feedback. Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/506.

**Closed by m417z** 2024-04-26 17:12 UTC
Labels: mod-enhancement

**Comment by HMwancheng** [comment] 2024-04-27 00:39
GET! TKS!
