### ISSUE TITLE
"Disable grouping on taskbar" doesn't work in Windows 11 24H2

### ISSUE THREAD

**Issue by jlahijani** [ramensoftware/windhawk-mods#647] opened 2024-05-04 16:02 UTC
@m417z I'm using Windows 24H2 (since I'm using Windows Insider Dev Channel) and it seems the "Disable grouping on taskbar" mod no longer works.

Here is the debug log, but it does contain `HTTP_STATUS_NOT_FOUND`:
```
DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
08:57:21.341 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
08:57:21.341 8788 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.26120
08:57:21.341 8788 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.4.1
08:57:21.341 8788 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: taskbar-grouping
08:57:21.341 8788 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.3.1
08:57:21.342 8788 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFA45F70000
08:57:21.342 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
08:57:21.342 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
08:57:21.342 8788 explorer.exe  [WH] [taskbar-grouping] [1606:Wh_ModInit]: >
08:57:21.342 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.342 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: pinnedItemsMode
08:57:21.342 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: pinnedItemsMode
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: replace
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: placeUngroupedItemsTogether
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: placeUngroupedItemsTogether
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 0
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: useWindowIcons
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: useWindowIcons
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 0
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: excludedPrograms[%d]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: excludedPrograms[0]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: excluded1.exe
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: excludedPrograms[%d]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: excludedPrograms[1]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: 
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: customGroups[%d].name
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: customGroups[0].name
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: Group 1
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: customGroups[%d].items[%d]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: customGroups[0].items[0]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: group1-program1.exe
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.343 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: customGroups[%d].items[%d]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: customGroups[0].items[1]
08:57:21.343 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: group1-program2.exe
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: customGroups[%d].items[%d]
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: customGroups[0].items[2]
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: 
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: customGroups[%d].name
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: customGroups[1].name
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: 
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: groupingMode
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: groupingMode
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: regular
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: oldTaskbarOnWin11
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: oldTaskbarOnWin11
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 0
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
08:57:21.344 8788 explorer.exe  [WH] [taskbar-grouping] [1053:GetWindowsVersion]: Version: 10.0.26100.461
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-taskbar.dll
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 1#349131650#3010560#private: long __cdecl CTaskBand::CLauncherTask::_Launch(void)#191196#public: virtual long __cdecl CTaskGroup::SetAppID(unsigned short const *)#185664#protected: long __cdecl CTaskListWnd::_GetJumpViewParams(struct ITaskBtnGroup *,struct ITaskItem *,int,bool,struct Windows::Internal::Shell::JumpView::IJumpViewParams * *)const #1323252#public: virtual long __cdecl CTaskGroup::GetLauncherName(unsigned short * *)#158768#public: virtual bool __cdecl CTaskGroup::IsImmersiveGroup(void)#184448#public: virtual long __cdecl CTaskGroup::SetShortcutIDList(struct _ITEMIDLIST_ABSOLUTE const *)#1183456#protected: void __cdecl CTaskBand::HandleTaskGroupSwitchItemAdded(struct winrt::Windows::Internal::ComposableShell::Multitasking::ISwitchItem const &)#557388#public: virtual long __cdecl CTaskGroup::GetTitleText(struct ITaskItem *,unsigned short *,int)#158432#public: virtual int __cdecl CTaskGroup::GetNumItems(void)#488960#protected: void __cdecl CTaskBand::_UpdateI
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
08:57:21.344 8788 explorer.exe  [WH] [taskbar-grouping] [1229:HookSymbols]: Couldn't resolve all symbols from cache
08:57:21.344 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol3
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Module: 00007FFA42B80000
08:57:21.344 8788 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Path: C:\WINDOWS\SYSTEM32\taskbar.dll
08:57:21.355 8788 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Version: 10.0.26100.461
08:57:21.356 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
08:57:21.357 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.pdb\F1A5C726246FEBC12957F54DE28C2B7A1\Taskbar.pdb - path not found
08:57:21.357 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.pdb\F1A5C726246FEBC12957F54DE28C2B7A1\Taskbar.pd_ - path not found
08:57:21.357 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.pdb\F1A5C726246FEBC12957F54DE28C2B7A1\file.ptr - path not found
08:57:21.357 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/index2.txt
08:57:21.418 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
08:57:21.418 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.pdb/F1A5C726246FEBC12957F54DE28C2B7A1/Taskbar.pdb
08:57:21.476 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
08:57:21.476 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.pdb/F1A5C726246FEBC12957F54DE28C2B7A1/Taskbar.pd_
08:57:21.527 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
08:57:21.527 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.pdb/F1A5C726246FEBC12957F54DE28C2B7A1/file.ptr
08:57:21.580 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
08:57:21.580 8788 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x80190194
08:57:21.581 8788 explorer.exe  [WH] [LoadedMod::LogFunctionError]: Mod taskbar-grouping error: engine\symbol_enum.cpp(201)\windhawk.dll!00007FFA4F94CD74: (caller: 00007FFA4F93A66E) Exception(3) tid(2760) 806D0005 
08:57:21.581 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol3
08:57:21.581 8788 explorer.exe  [WH] [taskbar-grouping] [1234:HookSymbols]: Wh_FindFirstSymbol failed
08:57:21.581 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
08:57:21.581 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::~LoadedMod
08:57:21.581 8788 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::~LoadedMod

```

**Comment by m417z** [comment] 2024-05-04 16:06
Currently there's a problem which caused the required symbol files to become unavailable. For details, see [the relevant blog post](https://ramensoftware.com/windhawk-and-symbol-download-errors). Currently, the focus is to implement a workaround for non-preview builds. Preview builds are unlikely to be supported until Microsoft makes the debug symbol files available again, which they claim will hopefully be resolved in a week.

**Comment by m417z** [comment] 2024-05-18 22:06
Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/685.

**Closed by m417z** 2024-05-18 22:06 UTC
Labels: mod-bug
