### ISSUE TITLE
[Taskbar height and icon size] Widget icon not showing

### ISSUE THREAD

**Issue by Feliks-WR** [ramensoftware/windhawk-mods#670] opened 2024-05-09 13:45 UTC
The icon disappears, even if I make size identical to Windows 11 defaults.

**Comment by m417z** [comment] 2024-05-09 15:18
You're using a right-to-left user interface, perhaps it's related. Can you temporarily switch to English and see if the issue is fixed in this case?

**Comment by Feliks-WR** [comment] 2024-05-09 16:12
Okay, I'll try...
________________________________
منجانب: Michael Maltsev ***@***.***>
‏‏بھیجا گیا: 09 مئی, 2024 20:18
بطرف: ramensoftware/windhawk-mods ***@***.***>
Cc: Feliks-WR ***@***.***>; Author ***@***.***>
‏‏موضوع: Re: [ramensoftware/windhawk-mods] [Taskbar height and icon size] Widget icon not showing (Issue #670)


You're using a right-to-left user interface, perhaps it's related. Can you temporarily switch to English and see if the issue is fixed in this case?

**Comment by Feliks-WR** [comment] 2024-05-09 16:14
![image](https://github.com/ramensoftware/windhawk-mods/assets/73439021/62213f2b-8c9c-4187-8c8d-d25bb7ab58bd)

**Comment by m417z** [comment] 2024-05-09 17:28
OK, thanks for checking, I'll try to reproduce it. What's the version of your Windows, and of your Taskbar.View.dll file (C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll)?

**Comment by Feliks-WR** [comment] 2024-05-10 06:51
Taskbar.dll file: 624.7317.60.0
Windows: Edition     Windows 11 Pro
Version     23H2
Installed on      ‏27/‏08/‏1445
OS build    22631.3527
Experience  Windows Feature Experience Pack 1000.22700.1003.0
________________________________
منجانب: Michael Maltsev ***@***.***>
‏‏بھیجا گیا: 09 مئی, 2024 22:28
بطرف: ramensoftware/windhawk-mods ***@***.***>
Cc: Feliks-WR ***@***.***>; Author ***@***.***>
‏‏موضوع: Re: [ramensoftware/windhawk-mods] [Taskbar height and icon size] Widget icon not showing (Issue #670)


OK, thanks for checking, I'll try to reproduce it. What's the version of your Windows, and of your Taskbar.View.dll file (C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll)?

**Comment by m417z** [comment] 2024-05-10 11:18
Thank you for the information, fixed in version 1.2.7 of the mod.

**Comment by Feliks-WR** [comment] 2024-05-16 12:15
Hmmm... so, the same problem?
________________________________
منجانب: bancalero ***@***.***>
‏‏بھیجا گیا: 16 مئی, 2024 17:14
بطرف: ramensoftware/windhawk-mods ***@***.***>
Cc: Feliks-WR ***@***.***>; Author ***@***.***>
‏‏موضوع: Re: [ramensoftware/windhawk-mods] [Taskbar height and icon size] Widget icon not showing (Issue #670)


Hey, just updated Windows yesterday and my widget icon disappeared. Also updated and reinstalled the mod but as soon as I activate it, the icon disappears. I'm on regular Windows 11 Pro

**Comment by bancalero** [comment] 2024-05-16 12:18
unfortunately yes

My Windows 11 pro version if it helps:
23H2 - 22631.3593

**Comment by m417z** [comment] 2024-05-19 10:20
@bancalero I couldn't reproduce it, are you sure that you're using the latest version of the mod, 1.2.7?
What are your mod settings?
Any idea how I can reproduce it?

**Comment by bancalero** [comment] 2024-05-20 12:16
Yeah, I'm on 1.2.7 indeed :/
Here is a screenshot of my settings, as well of the taskbar with and without the mod:

Settings:
![Windhawk 20_05_2024 09_12_11](https://github.com/ramensoftware/windhawk-mods/assets/106411120/9f9b3680-c250-47b0-82eb-07615139f32e)

With mod:
![Captura de tela 2024-05-20 091237](https://github.com/ramensoftware/windhawk-mods/assets/106411120/11e822c4-f10b-49ec-b70a-0a3d73ab8392)

Without mod:
![Captura de tela 2024-05-20 091307](https://github.com/ramensoftware/windhawk-mods/assets/106411120/cea09b33-54ee-4e26-a915-ee15df15890b)

Cant think of any way to reproduce it, windows just updated and the icon is gone, didn't change any settings in months :(

**Comment by Maaxgg** [comment] 2024-05-30 14:25
> Fiz alguns testes e parece que se eu alterar o tamanho do ícone para qualquer valor inferior a 32, o ícone do clima desaparece. Só posso usar 32 ou superior no tamanho do ícone.
> 
> tamanho 32 ![imagem](https://private-user-images.githubusercontent.com/106411120/334525598-687e4140-d493-4a59-9f7a-40bed91ebe39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzkyODUsIm5iZiI6MTcxNzA3ODk4NSwicGF0aCI6Ii8xMDY0MTExMjAvMzM0NTI1NTk4LTY4N2U0MTQwLWQ0OTMtNGE1OS05ZjdhLTQwYmVkOTFlYmUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxNDIzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmVkNjFjMzVkNDJlZGI5ZGU5NDJkNWQwMTFlZWZmNTVkMGFiMGM4Y2Y2NjQ5YTQ0MTg5MmMzNDdiMjlkM2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LF9Lu5j6zTvAdDlXhEmRV0fmKKlaenENOdTzwabUuJ0)
> 
> tamanho 31 ![imagem](https://private-user-images.githubusercontent.com/106411120/334525694-060aab7c-6da0-45b8-9049-efce59bcbed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzkyODUsIm5iZiI6MTcxNzA3ODk4NSwicGF0aCI6Ii8xMDY0MTExMjAvMzM0NTI1Njk0LTA2MGFhYjdjLTZkYTAtNDViOC05MDQ5LWVmY2U1OWJjYmVkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxNDIzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDk2MzU4Y2QyZmM2MjMxNjJkZmMwOGU3YjQ2NjlmNWQ5NGJmNDE4NWFhNDlkZTI5NjkxMmRmODJkNGU2NzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oDUn-Zp8PagcDpYnQCKd5RL1SM2TEA2qZKF3MOLFo1Y)
> 
> Outras configurações não parecem afetar o ícone do clima
> 
> Alguma ideia do que deveria ser? O tamanho do ícone 32 é muito grande hahaha

I have the same problem, did you manage to solve it?

**Comment by bancalero** [comment] 2024-05-30 17:12
> I have the same problem, did you manage to solve it?

Unfortunately not yet, just hoping that @m417z find something when he can :)

**Comment by m417z** [comment] 2024-05-31 14:47
Fixed in Taskbar height and icon size v1.2.8. Please try it to confirm.

**Closed by m417z** 2024-05-31 14:47 UTC
Labels: info-needed, mod-bug

**Comment by toanphuong** [comment] 2024-06-01 02:13
> Fixed in Taskbar height and icon size v1.2.8. Please try it to confirm.

Weather Widget now perfectly working with the Taskbar height and Icon size mod! Thanks for your support!

**Comment by bancalero** [comment] 2024-06-01 18:17
> Fixed in Taskbar height and icon size v1.2.8. Please try it to confirm.

Yeah it's fixed! Thank you for your hard work!
