### ISSUE TITLE
[Bug report] Taskbar height and icon size + collapsing taskbar misplaces the taskbar on multi-monitor setups

### ISSUE THREAD

**Issue by NotSpaulding** [ramensoftware/windhawk-mods#313] opened 2023-09-24 18:19 UTC
If you decrease the height of the taskbar using @m417z's `taskbar-icon-size` and have the "Automatically hide the taskbar" option enabled (in Windows settings) the taskbar on your secondary monitor will be floating when you expand it.

Example: 
![A recording showing the taskbar floating when the "Automatically hide the taskbar" option is enabled](https://github.com/ramensoftware/windhawk-mods/assets/97350911/976dc7ad-9687-4192-873f-f8412225d080)

**Comment by m417z** [comment] 2023-11-29 16:33
Duplicate of https://github.com/ramensoftware/windhawk-mods/issues/380, fixed in Taskbar height and icon size v1.2.2.

**Closed by m417z** 2023-11-29 16:33 UTC
Labels: mod-bug

**Comment by NotSpaulding** [comment] 2023-11-29 17:12
Thanks!
