### ISSUE TITLE
Windows 24H2 update :) - Taskbar height and icon size do not work

### ISSUE THREAD

**Issue by toanphuong** [ramensoftware/windhawk-mods#702] opened 2024-05-29 07:32 UTC
Seems to load icons bug for the new Windows update :) . This is debug log:

```
14:22:50.355 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
14:22:50.356 11636 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.26100
14:22:50.356 11636 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.4.1
14:22:50.356 11636 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: taskbar-icon-size
14:22:50.356 11636 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.2.7
14:22:50.356 11636 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FF8E1B10000
14:22:50.357 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
14:22:50.357 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
14:22:50.357 11636 explorer.exe  [WH] [taskbar-icon-size] [1296:Wh_ModInit]: >
14:22:50.357 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
14:22:50.357 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: IconSize
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: IconSize
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 16
14:22:50.358 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
14:22:50.358 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarHeight
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarHeight
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 32
14:22:50.358 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
14:22:50.358 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarButtonWidth
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarButtonWidth
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 36
14:22:50.358 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
14:22:50.358 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
14:22:50.358 11636 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-Taskbar.View.dll
14:22:50.359 11636 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 1#1712961475#8540160#public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const #463012#public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)#677056#public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)#2902292#private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)#677260#__real@4048000000000000#7200328#public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const #3
14:22:50.359 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
14:22:50.359 11636 explorer.exe  [WH] [taskbar-icon-size] [839:HookSymbols]: Couldn't resolve all symbols from cache
14:22:50.359 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol3
14:22:50.359 11636 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Module: 00007FF901360000
14:22:50.359 11636 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Path: C:\WINDOWS\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll
14:22:50.359 11636 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Version: 2024.8604.0.0
14:22:50.362 11636 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
14:22:50.363 11636 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  PATH: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\40EAD95A3FE24E4F84379EFFD63BE5D71\Taskbar.View.pdb
14:22:50.363 11636 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x00000000
14:22:50.368 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol3
14:22:50.882 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:50.882 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF901380720
14:22:50.882 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11970
14:22:50.882 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:50.882 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF901380720: public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const 
14:22:50.905 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:50.905 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9016846B0
14:22:50.905 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11D00
14:22:50.905 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:50.905 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9016846B0: public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)
14:22:50.909 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:50.909 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF901610628
14:22:50.909 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11D50
14:22:50.910 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:50.910 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF901610628: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)
14:22:50.921 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:50.921 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF90158D78C
14:22:50.921 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11DD0
14:22:50.921 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:50.921 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF90158D78C: private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
14:22:50.933 11636 explorer.exe  [WH] [taskbar-icon-size] [762:operator()]: Found 00007FF901A53E68: __real@4048000000000000
14:22:50.935 11636 explorer.exe  [WH] [taskbar-icon-size] [762:operator()]: Found 00007FF90167C684: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const 
14:22:51.011 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:51.012 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF90156F294
14:22:51.012 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11F60
14:22:51.012 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:51.012 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF90156F294: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::SystemTray::SystemTrayFrame>::Height(double)const 
14:22:51.017 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:51.017 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF90158D744
14:22:51.017 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11F10
14:22:51.017 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:51.017 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF90158D744: private: void __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::UpdateFrameSize(void)
14:22:51.057 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:51.057 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9015C3CA0
14:22:51.058 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11F80
14:22:51.058 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:51.058 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9015C3CA0: private: void __cdecl winrt::Taskbar::implementation::TaskbarController::OnFrameSizeChanged(void)
14:22:51.117 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:51.117 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF901600AF0
14:22:51.117 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B12030
14:22:51.117 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:51.117 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF901600AF0: protected: virtual void __cdecl winrt::Taskbar::implementation::AugmentedEntryPointButton::UpdateButtonPadding(void)
14:22:51.128 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:51.128 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9013A872C
14:22:51.128 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11E30
14:22:51.128 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:51.128 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9013A872C: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
14:22:51.135 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:51.135 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF90156F1F4
14:22:51.135 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B12080
14:22:51.135 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:51.135 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF90156F1F4: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Windows::UI::Xaml::Controls::Primitives::RepeatButton>::Width(double)const 
14:22:51.164 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
14:22:51.164 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF90138DB68
14:22:51.164 11636 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF8E1B11D30
14:22:51.164 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
14:22:51.164 11636 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF90138DB68: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
14:22:51.168 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindCloseSymbol
14:22:51.173 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindCloseSymbol
14:22:51.173 11636 explorer.exe  [WH] [taskbar-icon-size] [864:HookSymbols]: Optional symbol 5 doesn't exist
14:22:51.173 11636 explorer.exe  [WH] [taskbar-icon-size] [860:HookSymbols]: Unresolved symbol: 9
14:22:51.173 11636 explorer.exe  [WH] [taskbar-icon-size] [962:HookSymbolsWithOnlineCacheFallback]: HookSymbols() failed, trying to get an online cache
14:22:51.173 11636 explorer.exe  [WH] [taskbar-icon-size] [1014:HookSymbolsWithOnlineCacheFallback]: Looking for an online cache at https://ramensoftware.github.io/windhawk-mod-symbol-cache/taskbar-icon-size/symbol-cache-taskbar.view.dll/1711496221-8630272.txt
14:22:51.249 11636 explorer.exe  [WH] [taskbar-icon-size] [1018:HookSymbolsWithOnlineCacheFallback]: Failed to get online cache
14:22:51.249 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
14:22:51.249 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::~LoadedMod
14:22:51.249 11636 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::~LoadedMod
```

**Comment by m417z** [comment] 2024-05-29 08:13
Thanks for reporting. Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/562.

**Closed by m417z** 2024-05-29 08:13 UTC
Labels: mod-bug
