### ISSUE TITLE
Windows 11's KB5032288 update breaks Windows Explorer/taskbar mods

### ISSUE THREAD

**Issue by CAJElevado** [ramensoftware/windhawk-mods#398] opened 2023-11-29 03:17 UTC
KB5032288 (Windows 11 Builds 22621.2787 and 22631.2787) is currently only available in Insider's Release Preview channel. I just wanna give you guys a heads-up about this update, which might go public soon. It seems to break Explorer and taskbar mods, such as Taskbar Thumbnail Reorder and Explorer 32px Icons. I'm not sure if it breaks other mods, but Text Replace works fine with KB5032288. Uninstalling KB5032288 fixes the issue for me.

**Comment by m417z** [comment] 2023-12-01 09:23
Apparently the problem is that Microsoft didn't publish debug symbols for this insider build, see:
https://github.com/ramensoftware/windhawk-mods/issues/406#issuecomment-1835749519

Closing as it's a known limitation of these Windhawk mods - they require debug symbols to work.

**Closed by m417z** 2023-12-01 09:23 UTC
Labels: mod-bug

**Comment by queenbiscuit311** [comment] 2023-12-03 13:34
Good to know, I "downgraded" to release windows 11 so that I didnt have this issue anymore.

**Comment by CAJElevado** [comment] 2023-12-03 22:37
My apologies for the lack of replies. I'm busy with other stuff atm.
