### ISSUE TITLE
@m417z [Classic Explorer navigation bar] no address bar at all when explorer is spawned by 3rd party applications

### ISSUE THREAD

**Issue by elbadcode** [ramensoftware/windhawk-mods#519] opened 2024-02-10 07:04 UTC
The mod works perfectly when launched normally but if I open explorer from another application, e.g. clicking show in explorer in unreal engine, premiere, etc. it spawns the new window with no address bar at all making it impossible to navigate and forcing me to restart explorer all together

**Comment by m417z** [comment] 2024-02-12 21:14
Which configuration are you using? Classic navigation bar or Classic ribbon UI (no tabs)?

Are you using [the option to launch folder windows in a separate process](https://www.elevenforum.com/t/enable-or-disable-launch-folder-windows-in-a-separate-process-in-windows-11.10080/)?

**Comment by m417z** [comment] 2024-02-15 16:00
Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/487.

**Closed by m417z** 2024-02-15 16:00 UTC
Labels: mod-bug
