### ISSUE TITLE
vertical taskbar mod not working after windows 11 update Build 27764

### ISSUE THREAD

**Issue by hao365** [ramensoftware/windhawk-mods#1334] opened 2024-12-12 03:11 UTC
![微信截图_20241212111050](https://github.com/user-attachments/assets/04ab2245-5acb-48ac-be7a-1966e4462088)

**Comment by m417z** [comment] 2024-12-12 04:12
Looks like a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/1271, see my comment with a workaround in that issue. Let me know if it's a different issue.

**Closed by m417z** 2024-12-12 04:12 UTC
Labels: mod-bug

**Comment by hao365** [comment] 2024-12-23 19:54
Resolved, Thx.
