### ISSUE TITLE
[Taskbar Styler] Update 1.3.3 broke taskbar background styling

### ISSUE THREAD

**Issue by ber-sma** [ramensoftware/windhawk-mods#709] opened 2024-05-31 09:19 UTC
An entry of the form:
* Target: Rectangle#BackgroundFill
* Styles: Fill=#FF565582

does not work anymore. Taskbar background cannot be styles. Even though I have "None" selected as theme, I suspect this bug is related to the addition of the TranslucentTaskbar theme.

**Comment by m417z** [comment] 2024-05-31 09:21
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by ber-sma** [comment] 2024-05-31 09:30
Here is the log: [taskbar-styler-1.3.3-no-background.txt](https://github.com/user-attachments/files/15511421/taskbar-styler-1.3.3-no-background.txt)
And I confirm that the taskbar background still does not work (and did work before the 1.3.3 update, but I don't know which version I was on before that).

**Comment by m417z** [comment] 2024-05-31 09:32
I believe that I know what the problem is. I'll look into fixing it soon.

**Comment by ber-sma** [comment] 2024-05-31 09:35
Can I downgrade the mod version somehow?

**Comment by m417z** [comment] 2024-05-31 09:38
Yes, you can disable the current mod, then copy the code of a previous version from a link in the changelog. Then, create a new mod in Windhawk, paste the mod code and compile it.

**Comment by ber-sma** [comment] 2024-05-31 10:31
Awesome! I went back to v1.3.2 and the bug is not present there - background styling works again.

**Comment by m417z** [comment] 2024-05-31 11:10
I believe it's fixed now in Windows 11 Taskbar Styler v1.3.4, please try it to confirm.

**Closed by m417z** 2024-05-31 11:10 UTC
Labels: mod-bug

**Comment by ber-sma** [comment] 2024-05-31 11:36
I confirm this to be fixed in v1.3.4.

You, sir, are amazing!
