### ISSUE TITLE
[Taskbar Labels for Windows 11] Only label certain process not working

### ISSUE THREAD

**Issue by Memphizzz** [ramensoftware/windhawk-mods#602] opened 2024-04-18 13:42 UTC
Hello,

I'm trying to use the mod for a couple of specific applications only (Visual Studio for example), so I enabled "Ignore mod inclusion/exclusion lists" and added "notepad.exe" and "devenv.exe" to the "Custom process inclusion list".
Unfortunately none of the applications show a label in my taskbar. I can see the mod working with default settings but can't get it to work for only these two applications.

My Mod settings:
`{"taskbarItemWidth":"160","minimumTaskbarItemWidth":"50","maximumTaskbarItemWidth":"176","runningIndicatorStyle":"fullWidth","progressIndicatorStyle":"sameAsRunningIndicatorStyle","fontSize":"12","leftAndRightPaddingSize":"8","spaceBetweenIconAndLabel":"8","labelForSingleItem":"%name%","labelForMultipleItems":"[%amount%] %name%"}`
Custom process inclusion list: 
notepad.exe
devenv.exe
Custom process exclusion list:
<none>
Ignore mod inclusion/exclusion lists:
enabled

OS: Windows 11 (Version 23H2, 22631.3447)

Any help is appreciated! Thanks in advance!

**Comment by m417z** [comment] 2024-04-19 10:03
The inclusion/exclusion list doesn't do what you expect in this case, please see my comment here: https://github.com/ramensoftware/windhawk-mods/issues/203#issuecomment-1927180436
Closing as a duplicate of the above issue.

**Closed by m417z** 2024-04-19 10:03 UTC
Labels: mod-bug
