### ISSUE TITLE
[Taskbar height and icon size] icon disappeared randomly

### ISSUE THREAD

**Issue by boyangma** [ramensoftware/windhawk-mods#456] opened 2023-12-29 03:43 UTC
Hi,

I found a bug when I was using [Taskbar height and icon size] mod. 
The problem was that the icon of an opened app in the taskbar would disappear randomly, it could be recovered if I click the app.
Actually, I'm not sure this bug is caused by this mod, but this never happened before I started to use Windhawk.  

![1](https://github.com/ramensoftware/windhawk-mods/assets/44192118/ac18c115-787f-4d46-b0b4-fe2e9fc293d5)

@m417z

**Comment by m417z** [comment] 2023-12-29 12:16
I saw multiple such bug reports which are unrelated to Windhawk. For example:
https://www.google.com/search?q=reddit+Windows11+icon+disappear

If you're certain that it's somehow related to the mod, please provide details to reproduce the issue, although I believe that it's unrelated.

**Comment by m417z** [comment] 2024-10-19 00:29
Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/903.

**Closed by m417z** 2024-10-19 00:29 UTC
Labels: info-needed, mod-bug
