### ISSUE TITLE
[Taskbar minimize/restore on scroll] doesn't work "Scroll over taskbar buttons" option on new win11 build

### ISSUE THREAD

**Issue by duk6046** [ramensoftware/windhawk-mods#273] opened 2023-08-19 07:21 UTC
23h2 beta 22631.2199
still work **Scroll over thumbnail previews** option.
**Cycle taskbar buttons with mouse wheel** mod is also not work anymore.

**Comment by HenryTheVacuum** [comment] 2023-08-30 19:03
it also doesn't work when using x-mouse program

**Comment by m417z** [comment] 2023-09-01 10:05
> it doesn't open windows that are on a different virtual desktop

Right, that's by design.

> it also doesn't work when using x-mouse program

I'm using X-Mouse Button Control and it works for me. Check your settings, make sure that you're using the latest version, and if it still doesn't work, contact the author for help.

Also, this issue is about incompatibility with Windows 11 23H2 beta 22631.2199. Please don't post your comments on unrelated issues.

**Comment by m417z** [comment] 2023-11-29 16:30
Probably fixed in version 1.1.2 of the mod. If not, please let me know.

**Closed by m417z** 2023-11-29 16:30 UTC
Labels: mod-bug

**Comment by m417z** [comment] 2023-11-30 15:49
Yes, I meant 1.0.5. For the virtual desktops issue, I haven't looked at it yet, let's track it here: https://github.com/ramensoftware/windhawk-mods/issues/295
