### ISSUE TITLE
Taskbar height and icon size: Taskbar gets pushed offscreen on reboot until restarting explorer

### ISSUE THREAD

**Issue by superluig164** [ramensoftware/windhawk-mods#529] opened 2024-02-17 22:20 UTC
@m417z 
On some of my devices (I believe this is affected by touch mode being available) when I reboot, the taskbar gets pushed down below the screen once this mod loads.  It seems like it's getting set at the height of the touch mode taskbar, even though that feature is disabled.  Apps and menus adhere to the correct size, but all the visual elements get pushed down.  When I restart explorer, it fixes itself.  I'm not sure what the bug is, I'd be happy to help test, but perhaps the mod could just restart explorer after it loads?

**Comment by m417z** [comment] 2024-03-02 10:10
Perhaps similar to this issue: https://github.com/ramensoftware/windhawk-mods/issues/413

Does locking the computer (Win+L) and unlocking fix it? If it does, it can be used as a workaround until there's a better fix.

**Comment by superluig164** [comment] 2024-03-03 07:28
@m417z Unfortunately, no.  Locking the computer and unlocking it does not fix it.  If you need any more debug info let me know, I'll do what I can to help.

**Comment by m417z** [comment] 2024-03-06 19:53
I wasn't able to reproduce the issue, but I made some improvements and it might be fixed in Taskbar height and icon size v1.2.3. Please try it and let me know whether it's fixed for you. If not, I'll reopen the issue.

**Comment by superluig164** [comment] 2024-04-11 20:45
I still have this issue after updating to the latest version.  Locking and unlocking still doesn't fix it - only restarting Explorer.

**Comment by m417z** [comment] 2024-04-12 17:11
@superluig164 if you have a way to reproduce it, let me know. Meanwhile, as a workaround, try adding winlogon.exe, userinit.exe to the process inclusion list in the advanced settings. It will make it more likely for the mod to be loaded at an early stage.

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/79765094-e0c8-4f47-9989-988e5a66c034)

**Comment by superluig164** [comment] 2024-04-12 21:03
So far, the best way to reproduce it that I have found is to reboot the computer - but sometimes that doesn't do it.  When I update Windows it almost always happens though.  If there's a way I can do a debug log or something to send you when it happens I'd be happy to do that, I just can't reboot the machine constantly since I need to use it.  I'd rather try to help you find the root cause of the problem than just work around it, if you know what I mean.

**Comment by superluig164** [comment] 2024-08-11 19:58
I'm still having this issue.  Something I noticed, is that, after the issue presented itself, I ran the Windhawk updater, and the taskbar remained displaced off the screen despite Windhawk no longer running.  This might be Windhawk exacerbating a bug already present in Windows Explorer.

**Comment by superluig164** [comment] 2024-08-12 21:01
@m417z Update to this issue: it's now consistently reproducible on my Surface Laptop Studio.  I'm not sure why it doesn't act the same way on my main machine, perhaps due to a different update.  When the mod is enabled, the taskbar becomes displaced below the bottom of the screen.  This behaviour sticks, even after disabling the mod, until restarting Explorer.  No amount of adjusting settings in Windows or the mod I've found to fix it.  I use the mod primarily to shrink the height of the taskbar.  Perhaps this is important.  Let me know if you'd like my configuration or for me to try and record a debug log while it happens.

Here's the details on my SLS:

Windows version: Version 23H2 (OS Build 22631.3958)
Windhawk 1.5.1
Taskbar height and icon size version 1.2.10

**Comment by RagibHasin** [comment] 2024-08-13 00:19
I am facing similar issues here.

Device: Asus ZenBook UM462DA (Touchscreen)
Windows version: Version 23H2 (OS Build 22631.3958)
Windhawk 1.5.1
Taskbar height and icon size version 1.2.10

The behavior was mitigable by restarting explorer before the latest Windows update. But now with the mod active, it is not mitigable at all.

As @superluig164 said, I also think it requires a touchscreen device to show up.

**Comment by superluig164** [comment] 2024-08-13 00:58
I will update my Surface Pro 7+ and check to see if the behaviour also happens on that device, just to confirm the touchscreen idea.  I'll also check with my mom's HP Pavilion desktop which also has a touchscreen.

**Comment by m417z** [comment] 2024-08-16 17:26
> Let me know if you'd like my configuration or for me to try and record a debug log while it happens.

Please see my comment here: https://github.com/ramensoftware/windhawk-mods/issues/859#issuecomment-2293870017.

**Comment by MuscularPuky** [comment] 2024-09-14 11:53
uh actually I already met this problem a year ago and bypassed with Task Scheduler trick. every time log on disable then enable Tablet Optimized Taskbar for 1~2s. although it's not fundamental but very effective for me. now I only meet this rarely when I connecting the external monitor

**Comment by m417z** [comment] 2024-09-17 18:43
If anyone here can still reproduce the problem, could you please try the following:

* Install [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler)
* Add the following styles in the mod settings, replace `40` with your configured taskbar height:
  * Target: `Taskbar.TaskbarFrame`
  * Styles: `Height=40`, `MaxHeight=40`

Let me know if the problem still occurs with this configuration.

**Comment by MuscularPuky** [comment] 2024-09-25 09:32
> If anyone here can still reproduce the problem, could you please try the following:
> 
> * Install [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler)
> * Add the following styles in the mod settings, replace `40` with your configured taskbar height:
>   
>   * Target: `Taskbar.TaskbarFrame`
>   * Styles: `Height=40`, `MaxHeight=40`
> 
> Let me know if the problem still occurs with this configuration.

No, it made the problem worse :(
there's separatly specified `ShyTablet` `TabletPosture` keys so we'd focus on them perhaps
MS started to force the tablet taskbar button size to sqaure—means no taskbar label anymore—since 23H2. but this limitation is only at the first load so we can still have a taskbar label supported tablet taskbar—means more compact sized—until restart explorer
I'm testing VerticalAlignment at taskbar.TaskbarFrame but Taskbar Styler seems lazy :( it keeps loss some styles

**Comment by MuscularPuky** [comment] 2024-09-25 09:38
> > If anyone here can still reproduce the problem, could you please try the following:
> > 
> > * Install [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler)
> > * Add the following styles in the mod settings, replace `40` with your configured taskbar height:
> >   
> >   * Target: `Taskbar.TaskbarFrame`
> >   * Styles: `Height=40`, `MaxHeight=40`
> > 
> > Let me know if the problem still occurs with this configuration.
> 
> No, it made the problem worse :( there's separatly specified `ShyTablet` `TabletPosture` keys so we'd focus on them perhaps MS started to force the tablet taskbar button size to sqaure—means no taskbar label anymore—since 23H2. but this limitation is only at the first load so we can still have a taskbar label supported tablet taskbar—means more compact sized—until restart explorer I'm testing VerticalAlignment at taskbar.TaskbarFrame but Taskbar Styler seems lazy :( it keeps loss some styles

the most problem is can't fix the state of taskbar to either desktop/tablet. when the tablet tskbar enabled first, the taskbar is desktop size. but after reload taskbar, now taskbar becomes tablet size, and it makes taskbar goes out of the screen

**Comment by m417z** [comment] 2024-09-25 09:41
@MuscularPuky this issue is not about tablet mode. Try this, let me know if it helps:
https://github.com/ramensoftware/windhawk-mods/issues/957#issuecomment-2364698203

**Comment by MuscularPuky** [comment] 2024-09-25 09:53
> Tablet

oh I'm sorry I confused the thread with same result
in my case each startup taskbar (48px) and after reloaded taskbar (72px) have different height so can't apply that solution :(

**Comment by m417z** [comment] 2024-09-25 10:35
@MuscularPuky try the linked version in the comment that I posted, does it improve anything? It tries to adjust the height in more cases.

**Comment by superluig164** [comment] 2024-10-16 14:19
I would just like to add to this that I have experienced this bug again after updating to Windows 11 24H2 (26100.2033) on my Surface Laptop Studio.  Like before, the taskbar stays displaced even after the mod is disabled, until I restart Explorer.  Hopefully this is a simple fix this time around.  Let me know if there's anything else I can do to try and help pinpoint the issue.

**Comment by superluig164** [comment] 2024-10-16 15:02
@m417z Yep, at least during this session, every time I enable the mod, the taskbar is displaced until I restart Explorer.  If there's a log I can get or some way to debug I'm happy to go through it.

**Comment by m417z** [comment] 2024-10-16 15:06
@superluig164 Please try this version in which I tried to improve this aspect:
https://github.com/m417z/my-windhawk-mods/blob/ebb65740bab659131de307e287e97de58868976e/mods/taskbar-icon-size.wh.cpp

To try it, disable the existing mods (Taskbar height and icon size, Windows 11 Taskbar Styler), restart explorer just to be sure, then click the bottom right button to create a new mod, replace the code with the code below, click "Compile Mod", then "Exit Editing Mode".

Let me know if there's any difference at all.

Next, if it doesn't help, please record some information with UWPSpy as I asked here:
https://github.com/ramensoftware/windhawk-mods/issues/957#issuecomment-2364776183

It's best to do it once with the official version, and once with my fix attempt. Before enabling each version, restart explorer.exe to reset all possible leftovers from the previous mod.

**Comment by superluig164** [comment] 2024-10-16 15:12
@m417z This version seems to work properly.  No displacement observed, yet.

**Comment by m417z** [comment] 2024-10-16 15:18
@superluig164 good to know. While we're still here and you're in this reproducible state, I'd love to collect more information since there's no other I know of to reproduce this.

Could you edit the test mode, comment (or remove) this line: `contentGrid.Height(height);`, disable it, compile it, restart explorer, enable it, and see whether the issue happens with this line commented?

**Comment by superluig164** [comment] 2024-10-16 15:29
@m417z With that line commented out, the taskbar is now displaced until Explorer is restarted, like the published version of the mod.  It looks like, at least for me, right now, that line fixes the problem.

**Comment by m417z** [comment] 2024-10-16 15:33
Great, it was an educated guess and I'm glad that it works.

Another check I'd like to be made if you have the time: users reported similar issues with the mods [Vertical Taskbar for Windows 11](https://windhawk.net/mods/taskbar-vertical), [Taskbar on top for Windows 11](https://windhawk.net/mods/taskbar-on-top), for example: 

![image](https://github.com/user-attachments/assets/5164d81a-5357-46c2-a7d0-9ffd79260b56)

Could you try both (each time restarting explorer before enabling the mods) and report back whether there are similar issues?

**Comment by m417z** [comment] 2024-10-17 12:12
@superluig164 thanks for the checks. I did some experiments with tablet mode on my computer, and I got a state which looks similar to what you describe. In this state, the taskbar's actual height is slightly larger than what's displayed:

![image](https://github.com/user-attachments/assets/bb226802-29d9-413f-b7c3-46dc66fd2e73)

While that extra height isn't visible, there are side-effect artifacts, such as the desktop selection rectangle and the right click menu:

https://github.com/user-attachments/assets/270d6cde-a60f-4beb-9f1e-b0a7ceef0857

Are you seeing the same (without any mods)?

It seems I'm able to get this state with:

* [TabletPostureTaskbar](https://www.elevenforum.com/t/turn-on-or-off-tablet-optimized-taskbar-in-windows-11.5133/)=1
* Enable taskbar on top mod
* TabletPostureTaskbar=0
* Disable taskbar on top mod

> Taskbar on top for Windows 11

Great, so it seems that the same around will work. I'll add it and will post a version to try.

> Vertical taskbar for Windows 11

This one looks more complex. I'll experiment with the new state I was able to achieve, hopefully I'll find a workaround and will post it for testing. Generally Vertical taskbar isn't compatible with Taskbar height and icon size (Taskbar on top too but it's less likely to conflict), so the goal is really to have Vertical taskbar alone work. A common problem users reported is that it's indeed just invisible.

> ideally, mods should leave no traces after being disabled, other than the Windhawk framework, or at least I think so

I agree, ideally... in practice, sometimes it requires a non-trivial amount of effort, and I prefer to focus on things that have a visible effect. Incompatibilities such as enabling and disabling mod X, then enabling conflicting mod Y without restarting explorer are low priority.

**Comment by m417z** [comment] 2024-10-17 13:09
> I do not experience the same thing, not with the test version nor with the published version.

So if I understand correctly, you don't see artifacts like in the video I posted? My suspicion was that you'll see the same without having any mods running. So if you didn't check that, please:

* Disable all related mods
* Restart explorer
* Check whether you see the "invisible extra height" artifacts as in the video (desktop selection and menu)

> the touch-optimized taskbar does behave less incorrectly using the test version

So any issues left with the test version?

And regarding taskbar on top, here's a test version with the same workaround, could you try it?
https://github.com/m417z/my-windhawk-mods/blob/7deafd07c3e96a7d084cb983fde54c446a8abe63/mods/taskbar-on-top.wh.cpp

* Disable all related mods
* Restart explorer
* Enable the test taskbar-on-top mod and see if it has quirks such as the gap between the taskbar and the top of the monitor

Thanks.

**Comment by superluig164** [comment] 2024-10-17 15:05
@m417z 
Ooooh my bad, you're right, with no height-related mods enabled, there is a space above the taskbar with the selection box.  I'm not sure what causes that.  Interesting that enabling the mods fixes it.  Taskbar on top also exhibits the displaced behaviour without the height mods enabled.  I'm almost not sure how I didn't notice before.

I think the test version is definitely an improvement over the published version - I would probably go ahead and release it for now.  I have yet to notice any anomalies using it regularly.

With this test version of Taskbar on top, at first, this happens:
![image](https://github.com/user-attachments/assets/a85f3cc2-4c79-47e4-8dd7-9acd9f3d80d3)
After enabling and disabling the test version of taskbar height and icon size, it is fixed until restarting explorer, though the status icons are displaced a bit lower than they should be (regardless of on top or not.)  This is fixed if you restart explorer with the mod(s) enabled.

**Comment by m417z** [comment] 2024-10-17 15:32
> with no height-related mods enabled, there is a space above the taskbar with the selection box. I'm not sure what causes that

Great, at least my reproduction is somewhat close to what actually happens. And not all quirks are related to Windhawk :)

As to why, I assume it has something to do with tablet/touch-optimized mode.

> I think the test version is definitely an improvement over the published version - I would probably go ahead and release it for now

Yeah, I'll release it soon.

> With this test version of Taskbar on top, at first, this happens

Too bad, I hoped it's fixed. Just to make sure, is it after the steps I mentioned?

> - Disable all related mods
> - Restart explorer
> - Enable the test taskbar-on-top mod and see if it has quirks such as the gap between the taskbar and the top of the monitor

Does it make any difference if you first leave taskbar-on-top enabled (and the rest disabled), and then restart explorer?

What's the white bar just above Windhawk? What happens if you maximize Windhawk?

> After enabling and disabling the test version of taskbar height and icon size, it is fixed until restarting explorer

That's assuring, I just need to find out what it does to fix that.

**Comment by MuscularPuky** [comment] 2024-10-17 15:37
> @superluig164 Please try this version in which I tried to improve this aspect: https://github.com/m417z/my-windhawk-mods/blob/ebb65740bab659131de307e287e97de58868976e/mods/taskbar-icon-size.wh.cpp
> 
> To try it, disable the existing mod, restart explorer just to be sure, then click the bottom right button to create a new mod, replace the code with the code below, click "Compile Mod", then "Exit Editing Mode".
> 
> Let me know if there's any difference at all.
> 
> Next, if it doesn't help, please record some information with UWPSpy as I asked here: [#957 (comment)](https://github.com/ramensoftware/windhawk-mods/issues/957#issuecomment-2364776183)
> 
> It's best to do it once with the official version, and once with my fix attempt. Before enabling each version, restart explorer.exe to reset all possible leftovers from the previous mod.

OMG I suffered from Windows 11 Taskbar Styler with Tablet Mode for about 2y but now All things started working fine!! THX

**Comment by superluig164** [comment] 2024-10-17 15:59
@m417z 
To note, I keep touch-optimized mode disabled.  I did test turning it on for the earlier tests, but currently all my tests otherwise have it off.

> Too bad, I hoped it's fixed. Just to make sure, is it after the steps I mentioned?
Yes.  The white bar just above Windhawk was Firefox, maximized.

> Does it make any difference if you first leave taskbar-on-top enabled (and the rest disabled), and then restart explorer?
Yes, this works.  It only seems to cause this error if it's enabled later.  Restarting explorer with just the taskbar on top mod enabled, it works properly.  Actually, I think the displaced status icons are caused by this error.  If I restart explorer with only the taskbar on top mod enabled, they don't get displaced.  Only if I "fix" it by enabling the taskbar height mod.  (both test versions)

**Comment by m417z** [comment] 2024-10-17 16:31
> To note, I keep touch-optimized mode disabled

My guess is that it's something related to that, maybe it's not enabled but is still loaded due to the hardware and has side effects. But I don't really know.

> Yes, this works. It only seems to cause this error if it's enabled later.

Good, that's an improvement. As far as I understand, with the release taskbar-on-top version, it doesn't work properly even after restart, right?

For now, I guess I'll leave it as is, with a note that an explorer restart might be required for some devices. I'd love to find a workaround, but it's quite challenging without being able to reproduce this state and being able to try various things.

**Comment by superluig164** [comment] 2024-10-17 16:35
Yeah, the release version doesn't work unless I also enable (or enable and disable) the test version of height and icon size.  You might be able to use the same workaround temporarily.

**Comment by m417z** [comment] 2024-10-17 16:46
I thought about it, but I'd rather not bring big chunks of Taskbar height and icon size to Taskbar on top. The two seem to be compatible to some degree, I don't want to risk that.

OK, let's give it some extra testing. Could you try these variants and see if any of them behaves differently?
Same procedure:

- Disable all related mods
- Restart explorer
- Enable the test taskbar-on-top mod and see if it has quirks

* https://github.com/m417z/my-windhawk-mods/blob/3ad1686dd48e7853a618586252be50d297e149c0/mods/taskbar-on-top.wh.cpp
* https://github.com/m417z/my-windhawk-mods/blob/7fed3e4de4617e43d612229543c59ca028b9db56/mods/taskbar-on-top.wh.cpp

**Comment by superluig164** [comment] 2024-10-18 15:24
The first variant exhibits the same behaviour as before, with blank space below and above the taskbar.

The second variant is even worse!
![image](https://github.com/user-attachments/assets/7a51d426-cd74-46af-b292-d2819fc91af2)

**Comment by m417z** [comment] 2024-10-19 00:28
@superluig164 thanks, I gave up for now. I released updates to both "Taskbar height and icon size" (which hopefully solves this issue) and "Taskbar on top" (which requires restarting explorer but at least then it works).

I'll look at the vertical taskbar mod soon. I hope the same workaround will work for it too. I might need your help with it as well. Thanks!

**Closed by m417z** 2024-10-19 00:28 UTC
Labels: mod-bug

**Comment by superluig164** [comment] 2024-10-19 05:04
@m417z Feel free to ping me here or on any other related issues.  I'll do my best to help!

**Comment by m417z** [comment] 2024-10-19 14:24
@superluig164 thanks, I added a similar workaround to the vertical taskbar mod, please try it:
https://github.com/m417z/my-windhawk-mods/blob/429cde575f9b9440e7f4306f309b360008ac6b49/mods/taskbar-vertical.wh.cpp

Please make these two checks and let me know how it behaves:

1. Restart explorer, then load mod

- Disable all related mods
- Restart explorer
- Enable the test taskbar-vertical mod and see if it has quirks

2. Restart explorer while the mod is loaded

- Disable all related mods
- Enable the test taskbar-vertical mod
- Restart explorer, see if it has quirks

**Comment by superluig164** [comment] 2024-10-22 17:29
@m417z 

In both cases, the taskbar is invisible for a while, but eventually, it does appear and works.  However, the status icons and clock are aligned to the left instead of the center, causing the clock to be cut off.  The Start menu when opened also gets cut off, if you also use Windows 11 Start Menu Styler.  It seems to be limited to the default width.

![image](https://github.com/user-attachments/assets/2778b4c8-dfdf-41bc-ae9b-9cffc0853c11)

It looks a little weird with labels enabled but I imagine that's just because it's intended to be used without them.  (taskbar labels mod is disabled, just stock Windows labels.)

**Comment by m417z** [comment] 2024-10-22 18:38
> In both cases, the taskbar is invisible for a while, but eventually, it does appear and works

That's great progress from being invisible forever!

> However, the status icons and clock are aligned to the left instead of the center, causing the clock to be cut off

Not good, are you using other mods such as Windows 11 Taskbar Styler? I assume it happens in both scenarios, i.e. both restart-then-enable and enable-then-restart?

> The Start menu when opened also gets cut off, if you also use Windows 11 Start Menu Styler. It seems to be limited to the default width.

That's a known limitation which has a workaround, see https://github.com/ramensoftware/windhawk-mods/issues/1013.

> It looks a little weird with labels enabled but I imagine that's just because it's intended to be used without them

It's not perfect, but it was designed to be usable. configuring the taskbar to be wider should improve it. It was much less usable in earlier versions (https://github.com/ramensoftware/windhawk-mods/issues/886).

**Comment by m417z** [comment] 2024-10-22 20:57
@superluig164 I was able to reproduce the tray area misalignment issue, and hopefully was able to fix it. Please confirm by trying this version:
https://github.com/m417z/my-windhawk-mods/blob/186a81d88a70353a892de18f4317ba5c95555912/mods/taskbar-vertical.wh.cpp

**Comment by m417z** [comment] 2024-10-23 18:45
@superluig164 Thanks for confirming, just released an update! I think we're good for now, hopefully all major issues related to this tablet/touch mode are now resolved.

**Comment by superluig164** [comment] 2024-10-23 19:29
@m417z Happy to help, feel free to ping me anytime if you need someone to test any mods, particularly in a touch environment, but I'm happy to help with development or testing any way I can.

**Comment by m417z** [comment] 2025-02-07 17:25
@superluig164 ping :) do you still have the environment to test mods in the tablet/touchscreen-like environment?

I made a sensitive change for a new version of the Vertical Taskbar for Windows 11 mod, in order to make it compatible with a new Windows 11 build. I'm afraid that it might be incompatible with the tablet-like environment. Can you please try it?

https://github.com/m417z/my-windhawk-mods/blob/d8292b6d606bafe57381bc374686a0534a4c8c8a/mods/taskbar-vertical.wh.cpp

The checks, like last time:

**Comment by m417z** [comment] 2025-02-07 17:25
@superluig164 ping :) do you still have the environment to test mods in the tablet/touchscreen-like environment?

I made a sensitive change for a new version of the Vertical Taskbar for Windows 11 mod, in order to make it compatible with a new Windows 11 build. I'm afraid that it might be incompatible with the tablet-like environment. Can you please try it?

https://github.com/m417z/my-windhawk-mods/blob/d8292b6d606bafe57381bc374686a0534a4c8c8a/mods/taskbar-vertical.wh.cpp

The checks, like last time:

1. Restart explorer, then load mod

- Disable all related mods
- Restart explorer
- Enable the test taskbar-vertical mod and see if it has quirks

2. Restart explorer while the mod is loaded

- Disable all related mods
- Enable the test taskbar-vertical mod
- Restart explorer, see if it has quirks

Thanks!

**Comment by superluig164** [comment] 2025-02-07 18:05
@m417z absolutely!  I'll have a look tonight!

**Comment by superluig164** [comment] 2025-02-10 17:19
@m417z Everything seems to work great!  The only comment I'd have is, maybe add an option to disable the repositioning of the various flyouts.  It would serve as a good workaround for the incompatibility with the Start Menu Styler mod, as well as allowing those who like to use the touch gestures to have a better experience, as the swipe gestures still work from the same edges of the screen, but the flyouts open in their respositioned locations. (e.g. swiping from the right edge opens the notification panel, but it opens near the left edge if the taskbar is on the left)

Let me know if you need anything else!

**Comment by m417z** [comment] 2025-02-10 22:56
Great, thanks for verifying! Regarding the flyout repositioning, the first versions didn't do that, and I got feedback from many users that it's missing. After implementing it, nobody asked for an option to have it reverted. You have a good point about swipe gestures, I didn't think about that, but I assume touch screen Windows devices aren't popular enough for it to be an issue for many users. In any case, I'll keep this suggestion in mind, thanks.
