### ISSUE TITLE
Thumbnail reorder does not reorder taskbar labels when using the old Windows 10 taskbar

### ISSUE THREAD

**Issue by kwyntes** [ramensoftware/windhawk-mods#412] opened 2023-12-07 13:31 UTC
When using the old Windows 10 taskbar through Explorer Patcher (the appropriate setting for that is enabled in the mod's settings), reordering thumbnails does not reorder their respective labels in the taskbar itself.

(similar to #403)

**Comment by m417z** [comment] 2023-12-09 16:10
Fixed in version 1.0.4 of the mod. Interestingly, there was the same issue for both the old and the new taskbar, although the cause was completely unrelated.

**Closed by m417z** 2023-12-09 16:10 UTC
Labels: mod-bug
