### ISSUE TITLE
"Taskbar minimize/restore on Scroll" aka "taskbar-button-scroll" by @m417z is not working

### ISSUE THREAD

**Issue by blzz** [ramensoftware/windhawk-mods#1209] opened 2024-11-07 13:05 UTC
I did the debug-dance and am attaching the log as per instruction.

Don't really have more to add :)

Miss that mod!
[taskbar-button-scroll debug log.dbg.txt](https://github.com/user-attachments/files/17661899/taskbar-button-scroll.debug.log.dbg.txt)

Cheers!

**Comment by m417z** [comment] 2024-11-07 23:56
Looks like a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/1115. In any case, I believe that it's fixed now in version 1.0.7. Please try it and let me know if it works.

**Closed by m417z** 2024-11-07 23:56 UTC
Labels: mod-bug
