### ISSUE TITLE
widget temperature it disappeared W11 22631.3593 v23H2 mod Taskbar height and icon size v1.2.7 

### ISSUE THREAD

**Issue by Maaxgg** [ramensoftware/windhawk-mods#707] opened 2024-05-30 14:18 UTC
I noticed for a while that the program has been making the weather widget on the left of the taskbar disappear, with the program it disappears and without the program it returns

I'm sure it must be because of the mod Taskbar height and icon size
![2](https://github.com/ramensoftware/windhawk-mods/assets/168863192/800df70e-df28-4814-bd6a-dee176bbcbbf)
![1](https://github.com/ramensoftware/windhawk-mods/assets/168863192/b0f3e683-6f61-47d3-ac2e-882099edbce9)

**Comment by m417z** [comment] 2024-05-31 14:44
Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/670. I'm working on a fix.

**Closed by m417z** 2024-05-31 14:44 UTC
Labels: mod-bug
