### ISSUE TITLE
【Chrome/Edge scroll tabs with mouse wheel】working error

### ISSUE THREAD

**Issue by HMwancheng** [ramensoftware/windhawk-mods#239] opened 2023-06-11 12:27 UTC
(so sorry of my english is so bad)

what  happen?
use vertical tabs in Edge, and scrolling down/up to switch a tab

in the switched tab
![Clip_230611_202404](https://github.com/ramensoftware/windhawk-mods/assets/91036325/7ff29d63-8fea-46c3-9094-e7fdce4db9fb)

scrolling the page(like scrolling google search page, not scrolling on the tab bar), sometimes this mod working too
![Clip_230611_202517](https://github.com/ramensoftware/windhawk-mods/assets/91036325/88db0021-3b13-46bd-bb16-d318463b3e82)

**Comment by m417z** [comment] 2023-06-13 20:13
Hi, thanks for the report.

> in the switched tab

It seems to be the same as this bug (unfortunately not in English):
https://github.com/ramensoftware/windhawk-mods/issues/86

I know that it happens sometimes, but unfortunately, it's not very easy to fix.
Since an issue for this already exists, I'm closing this issue.

> scrolling the page(like scrolling google search page, not scrolling on the tab bar), sometimes this mod working too

The scrolling triggers in the vertical/horizontal tabs and in other elements outside of the page such as the title bar and the address bar. That's by design.

**Closed by m417z** 2023-06-13 20:13 UTC
