### ISSUE TITLE
[Slick Window Arrangement] Buggy behavior, resize frame freezes

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#516] opened 2024-02-08 18:59 UTC
-->@m417z
when I move a window to the left it freezes and does not reset. Also the gray frame which simulates the location of the application remains frozen (this does not happen all the time)

example:
![Capture d'écran 2024-02-08 190434](https://github.com/ramensoftware/windhawk-mods/assets/142233342/2640d2a5-d6e0-4d30-b2a2-449d61bf8be2)
also the cursor becomes transparent after that (only on the page which freezes)
here is the only thing I get in the mod logs:
DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
20:02:08.919 14744 MoUsoCoreWorker.exe  [WH] [slick-window-arrangement] [1095:Wh_ModInit]: Init
20:02:56.168 11856 VSCodium.exe  [WH] [slick-window-arrangement] [1095:Wh_ModInit]: Init
20:03:21.634 8516 VSCodium.exe  [WH] [slick-window-arrangement] [1095:Wh_ModInit]: Init

**Comment by m417z** [comment] 2024-02-09 17:29
Looks similar to this issue: https://github.com/ramensoftware/windhawk-mods/issues/56
Is it the same issue?

Note the workaround posted by one of the users which might be helpful:

> It just sticks into place like that. Using Win+arrow key fixes it temporarily though.

And my comment:

> I encountered this bug once or twice, but I didn't see it for a long time, probably not within the last year. If you find a way to reproduce it, let me know. I don't think the issue is directly caused by Slick Window Arrangement, but perhaps it makes it more likely to trigger as it causes more window movement events.

**Comment by gilnett** [comment] 2024-02-09 17:59
actually, it's the same problem
to reproduce it you can just take windhawk
we increase the distance of the snap(its bug faster if you increase the size of the snap)
slide the window of windhawk to the right or left of the screen. 
then let go of the application window.
after the window freezes.
and sometimes the screen flashes and then you no longer see the cursor on this application
also I tried to recover the logs but it does not detect anything except when it crashes

**Comment by gilnett** [comment] 2024-02-09 18:05
well I didn't say anything this time I have something (but it didn't crash. just the black screen and the invisible mouse bug) :
19:01:20.665 6328 explorer.exe  [WH] [windows-11-taskbar-styler] [1721:operator()]: Re-applying all styles for Windows.UI.Xaml.Shapes.Rectangle
19:01:21.383 6328 explorer.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 10296
19:01:21.383 6328 explorer.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 11236
19:01:21.383 6328 explorer.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 10304
19:01:21.383 6328 explorer.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 11112
19:01:21.383 9052 ApplicationFrameHost.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 5624
19:01:21.383 6328 explorer.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 7116
19:01:21.399 6328 explorer.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 6656
19:01:21.430 6232 IEDSearch.exe  [WH] [slick-window-arrangement] [990:SetWindowHookForUiThreadIfNeeded]: SetWindowsHookEx succeeded for thread 6380
19:01:26.162 6328 explorer.exe  [WH] [windows-11-taskbar-styler] [1695:operator()]: Re-applying style for Windows.UI.Xaml.Shapes.Rectangle
19:01:26.201 6328 explorer.exe  [WH] [windows-11-taskbar-styler] [1695:operator()]: Re-applying style for Windows.UI.Xaml.Shapes.Rectangle
19:01:44.690 6328 explorer.exe  [WH] [windows-11-taskbar-styler] [1695:operator()]: Re-applying style for Windows.UI.Xaml.Shapes.Rectangle

**Comment by m417z** [comment] 2024-03-08 15:59
> actually, it's the same problem
> to reproduce it you can just take windhawk
> we increase the distance of the snap(its bug faster if you increase the size of the snap)
> slide the window of windhawk to the right or left of the screen.
> then let go of the application window.
> after the window freezes.
> and sometimes the screen flashes and then you no longer see the cursor on this application
> also I tried to recover the logs but it does not detect anything except when it crashes

I'm not sure I see how the snap distance can help with the reproduction. In any case, I tried to reproduce it for a while, but without success. See video below. Any ideas for other things I can try?

https://github.com/ramensoftware/windhawk-mods/assets/4129781/d0bf825d-bb17-4580-b9ea-332423073678

**Comment by gilnett** [comment] 2024-03-11 18:21
@m417z
I don't really have any other way to achieve this.
but when "Taskbar height and icon size" is deactivated, the mod works well (I realized this recently)


https://github.com/ramensoftware/windhawk-mods/assets/142233342/7764057e-ef54-49e9-87a3-fa60e1588cfa

**Comment by m417z** [comment] 2024-10-01 06:08
A duplicate of https://github.com/ramensoftware/windhawk-mods/issues/56. Fixed in Slick Window Arrangement v1.0.2.

**Closed by m417z** 2024-10-01 06:08 UTC
Labels: mod-bug
