### ISSUE TITLE
[Taskbar height and icon size] Issue with the buttons on the left

### ISSUE THREAD

**Issue by MetricWrench** [ramensoftware/windhawk-mods#957] opened 2024-09-14 23:58 UTC
I'm fighting with the Win11 taskbar - the latest updates have made it big. I've applied the options for taskbar and icon size but I'm having an issue with the buttons on the left.
Can someone show me what I'm doing wrong or point me in the direction of how to solve this issue?

![Screenshot 2024-09-14 195658](https://github.com/user-attachments/assets/4804063e-eaba-4098-a3aa-4b23b35c0fea)

**Comment by m417z** [comment] 2024-09-16 19:50
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by MetricWrench** [comment] 2024-09-16 22:31
Here's the debug log.
[DbgViewMini v1.txt](https://github.com/user-attachments/files/17020815/DbgViewMini.v1.txt)

**Comment by m417z** [comment] 2024-09-17 06:23
I don't see anything wrong in the logs, and I wasn't able to reproduce this problem with the same Windows version and mod settings. Any idea what else could it be? Do you have any other customization tools or mods? Are you using tablet mode?

**Comment by MetricWrench** [comment] 2024-09-17 12:33
It's just on this Dell laptop that it's a problem. I've been fighting with M'soft's messing with the taskbar since Win11 on this machine. Every update makes it get huge - yes - like tablet mode. I've made sure tablet mode is not enabled, and I've  tried other explorer mods. Perhaps those are messing with Windhawk. I still have Winaero Tweaker installed. Could that be part of the problem?

**Comment by m417z** [comment] 2024-09-17 18:55
Could you try the following:

* Install [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler)
* Add the following styles in the mod settings, replace `34` with your configured taskbar height:
  * Target: `Taskbar.TaskbarFrame`
  * Styles: `Height=34`, `MaxHeight=34`

Let me know if the problem still occurs with this configuration.

**Comment by MetricWrench** [comment] 2024-09-17 22:56
That worked!!! Yay! Thanks for the support. I never thought I was going to get this issue resolved.

**Comment by m417z** [comment] 2024-09-20 22:25
Great. I tried to fix the mod to handle this case, can you please try the fix?

To try it, disable the existing mods (Taskbar height and icon size, Windows 11 Taskbar Styler), restart explorer just to be sure, then click the bottom right button to create a new mod, replace the code with the code below, click "Compile Mod", then "Exit Editing Mode".

https://github.com/m417z/my-windhawk-mods/blob/37262efafc338662f032052be113124012cd18cb/mods/taskbar-icon-size.wh.cpp

**Comment by MetricWrench** [comment] 2024-09-20 23:11
That seems to have created another issue, or I don't have the settings adjusted properly. I've attached before and after the mod screenshots.
![After Mod](https://github.com/user-attachments/assets/09391b6d-52a6-4713-b731-d469d472eea9)
![Mods off](https://github.com/user-attachments/assets/49530610-a3aa-455b-b7a6-97c095b3b3e2)

**Comment by m417z** [comment] 2024-09-21 00:20
Since I don't have an environment to reproduce it, it's tricky to solve, but let's try this, please record the following:
Run [UWPSpy](https://ramensoftware.com/uwpspy), inspect explorer.exe, locate the taskbar and go over some of the first elements, showing their sizes and properties, until the TaskbarBackground element, something like this:

https://github.com/user-attachments/assets/938ad69c-c568-457a-925f-28eb6f799914

**Comment by m417z** [comment] 2024-10-19 12:08
Hopefully fixed with the improvements in version 1.2.13 as discussed in https://github.com/ramensoftware/windhawk-mods/issues/529#issuecomment-2417127448. If not, please let me know and I'll reopen the issue.

**Closed by m417z** 2024-10-19 12:08 UTC
Labels: info-needed, mod-bug
