### ISSUE TITLE
Windhawk taskbar height and icon size does not work with Windows 24H2 v10.0.26100.1297

### ISSUE THREAD

**Issue by dbonner** [ramensoftware/windhawk-mods#814] opened 2024-07-26 06:35 UTC
Hi,
I opted for Windows Release Previews, thinking I would only be ahead of the normal release by a week or two at most.
Windhawk taskbar/icon size does not work at all after the latest cumulative update tow Windows 24H2.
Please let me know if there is a fix for this.
All the best,
Daniel

**Comment by m417z** [comment] 2024-07-27 12:11
Update KB5040527, which was released two days ago, introduced a change that made it incompatible with the mod. Should be fixed now in version 1.2.9.

Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/809.

**Closed by m417z** 2024-07-27 12:11 UTC

**Comment by 1aTa** [comment] 2024-07-28 02:54
The latest version (1.2.9) didn't fix this on 24H2 latest build 26100.1297.

**Comment by m417z** [comment] 2024-07-28 10:26
@1aTa 24H2 isn't supported, it's a known limitation and it's tracked here: https://github.com/ramensoftware/windhawk-mods/issues/562.

**Comment by AsvnDG** [comment] 2024-07-30 15:16
> I tried
> 
> ```
>   "controlStyles[24].target": "Windows.UI.Xaml.Controls.Image#Icon",
>   "controlStyles[24].styles[0]": "Height=20",
>   "controlStyles[25].target": "Microsoft.UI.Xaml.Controls.AnimatedVisualPlayer#Icon",
>   "controlStyles[25].styles[0]": "Height=20",
>   "controlStyles[25].styles[1]": "Width=20",
> ```
> 
> though it doesn2t change the taskbar height itself. just the icons.

For taskbar height, try this
Target: Taskbar.TaskbarFrame#TaskbarFrame
Style: Height=xx

change xx to your desired

**Comment by 1aTa** [comment] 2024-08-02 14:56
This works perfectly on 24H2 26100.1301, thank you @AsvnDG 🙏
