### ISSUE TITLE
[Taskbar height and Icon size] Windows 11 build 22631.3593 does not display the Icon and Text of the Weather Widget when the taskbar height is reduced

### ISSUE THREAD

**Issue by toanphuong** [ramensoftware/windhawk-mods#703] opened 2024-05-30 06:58 UTC
On Windows 11, I use the "Taskbar height and icon size" mod to reduce the height of the Taskbar, but this inadvertently prevents the Widget icon and the text of the Weather application from displaying on the Taskbar in Windows 11 build 22631.3593. Is there a way to adjust the icon and text of the Weather Widget so that it can display information on the Taskbar? I would appreciate any help with this. Thanks in advance!

![weather_widget](https://github.com/ramensoftware/windhawk-mods/assets/35450571/1462f9a8-7b37-4711-a164-bcff31d66ed0)

**Comment by Maaxgg** [comment] 2024-05-30 14:28
I have the same problem

**Comment by m417z** [comment] 2024-05-31 14:43
Closing as a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/670. I'm working on a fix.

**Closed by m417z** 2024-05-31 14:43 UTC
Labels: mod-bug
