### ISSUE TITLE
Start Menu Not Centered When Taskbar Is on Top "Taskbar on top for Windows 11 mod"

### ISSUE THREAD

**Issue by DreadBo1** [ramensoftware/windhawk-mods#1156] opened 2024-10-27 05:06 UTC
When using the "Taskbar on top for Windows 11" mod, the Start menu appears aligned to the left instead of being centered when the taskbar is positioned at the top. This only occurs when the taskbar is at the top; when it’s at the bottom, the Start menu is correctly centered.

Windows 11 version: 23H2

![Screenshot 2024-10-27 055340](https://github.com/user-attachments/assets/d4f5fffc-c09c-464e-a52c-c87921769710)

**Comment by m417z** [comment] 2024-10-27 07:49
I can't reproduce it, and I can't think for a reason for it to happen, as the mod only moves the start menu to top. It doesn't move it to the sides. Does disabling the mod fixes it? Restarting explorer?

**Comment by DefinitelyNotCherry** [comment] 2024-10-27 08:06
Reporting the same issue. Only happens when the Taskbar on Top mod is enabled. Goes back to the center when disabled. I only have this mod and Resource Redirect enabled.

**Comment by DreadBo1** [comment] 2024-10-27 08:09
Restarting Explorer didn’t fix it, and this issue only occurs when the mod is enabled.

**Comment by m417z** [comment] 2024-10-27 09:27
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by watchmakerful** [comment] 2024-10-27 10:20
Confirmed on Windows 11 23H2, but NOT confirmed on 24H2!

**Comment by DefinitelyNotCherry** [comment] 2024-10-27 13:59
[TOTW11Bottom.txt](https://github.com/user-attachments/files/17534095/TOTW11Bottom.txt)
[TOTW11SameasPrimary.txt](https://github.com/user-attachments/files/17534096/TOTW11SameasPrimary.txt)

I tried all options and selecting **Bottom** for "Taskbar location on secondary monitors" moved it to the center. Both "Same as Primary" and "Top" would align it back to the left. 

Windows 11 10.0.22631

I only have one monitor.

**Comment by m417z** [comment] 2024-10-27 22:12
I was trying to reproduce on 24H2. I'm able to reproduce it on 23H2. Some details:
* The issue was introduced in version 1.0.3 (Oct 19).
* It's caused by the attempt to change the incorrect jump list animation.

It's fixed now in version 1.0.4 by reverting the jump list animation change, only on Windows 11 23H2 and only if the icons are centered. Unfortunately I didn't find a way to fix it while keeping the correct jump list animation.

**Closed by m417z** 2024-10-27 22:12 UTC
Labels: info-needed, mod-bug

**Comment by DefinitelyNotCherry** [comment] 2024-10-27 22:16
> I was trying to reproduce on 24H2. I'm able to reproduce it on 23H2. Some details:
> 
>     * The issue was introduced in version 1.0.3 (Oct 19).
> 
>     * It's caused by the attempt to change the incorrect jump list animation.
> 
> 
> It's fixed now in version 1.0.4 by reverting the jump list animation change, only on Windows 11 23H2 and only if the icons are centered. Unfortunately I didn't find a way to fix it while keeping the correct jump list animation.

Thank you, sir!

**Comment by DreadBo1** [comment] 2024-10-27 22:36
> I was trying to reproduce on 24H2. I'm able to reproduce it on 23H2. Some details:
> 
>     * The issue was introduced in version 1.0.3 (Oct 19).
> 
>     * It's caused by the attempt to change the incorrect jump list animation.
> 
> 
> It's fixed now in version 1.0.4 by reverting the jump list animation change, only on Windows 11 23H2 and only if the icons are centered. Unfortunately I didn't find a way to fix it while keeping the correct jump list animation.

thank you!
