### ISSUE TITLE
"Disable grouping on taskbar" constantly resets icon groupings

### ISSUE THREAD

**Issue by derickso** [ramensoftware/windhawk-mods#259] opened 2023-07-21 01:47 UTC
Open a program (like an image viewer) and it appears on right most position of taskbar

After a few seconds, the icon will reset position and group with the other image viewer icons

**Comment by m417z** [comment] 2023-07-21 07:36
Is it Windows 10 or 11? Is the "Place ungrouped items together" option enabled? Can you post a video showing the bug?

**Comment by m417z** [comment] 2023-12-24 16:23
The issue is perhaps the same as https://github.com/ramensoftware/windhawk-mods/issues/423, which is now fixed. If not, please provide more details.

**Closed by m417z** 2023-12-24 16:23 UTC
Labels: info-needed, mod-bug
