### ISSUE TITLE
Taskbar on top for Windows 11: notification center open from botton

### ISSUE THREAD

**Issue by Cubody** [ramensoftware/windhawk-mods#1085] opened 2024-10-15 07:01 UTC
When using Taskbar on top for Windows 11:
If you have an empty notification center, it will be opened from the bottom

**Comment by m417z** [comment] 2024-10-15 08:22
A duplicate of https://github.com/ramensoftware/windhawk-mods/issues/1053. Check out the comments in that issue, there's also a workaround.

**Closed by m417z** 2024-10-15 08:22 UTC
Labels: mod-bug
